/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Money is an agreement", beats: [
    { dur: 6.61, line: "Take a note out of your pocket and really look at it. It is a piece of paper.", stage: "avatar(talk); show(coin)" },
    { dur: 8.61, line: "It buys bread because everyone agrees it does \u2014 not because the paper is worth anything by itself.", stage: "show(roti); banner(EVERYONE AGREES)" },
    { dur: 6.33, line: "Different places agree on different money. Cross a border, and the notes change.", stage: "avatar(point); cols(Here,There); sort(coin, a)" },
    { dur: 7.89, line: "The same slice of cake costs a different number in every country. The cake did not change.", stage: "show(cake); sort(cake, b); swap(cake)" },
    { dur: 7.65, line: "The agreement changed. That is all money is \u2014 the biggest agreement in the world.", stage: "avatar(smile); banner(THE BIGGEST AGREEMENT)" },
] };
