/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Needs and wants", beats: [
    { dur: 4.89, line: "Here is a question that looks easy and isn't.", stage: "avatar(talk)" },
    { dur: 10.73, line: "Some things, you would be in real trouble without. Food. A roof. Medicine when you are ill. Those are needs.", stage: "cols(Needs,Wants); show(roti); show(roof); show(medicine); sweep(a)" },
    { dur: 10.01, line: "Some things just make life nicer. A birthday cake. A video game. A gold chain, if you like that sort of thing.", stage: "show(cake); show(game); show(chain); sweep(b)" },
    { dur: 8.09, line: "Both are allowed. Nobody is in trouble for wanting things \u2014 wanting things is most of the fun.", stage: "avatar(smile)" },
    { dur: 6.37, line: "The trick is knowing which one you are looking at, before you pay.", stage: "avatar(point); banner(BEFORE YOU PAY)" },
    { dur: 3.69, line: "But watch this. Rain is coming.", stage: "avatar(talk); weather(rain)" },
    { dur: 8.41, line: "Today, an umbrella is a need. In dry May, the very same umbrella is a want.", stage: "show(umbrella); sort(umbrella, a); weather(sun); sort(umbrella, b)" },
    { dur: 8.05, line: "Same umbrella. Different day. Lots of things move between the two columns like that.", stage: "swap(umbrella)" },
    { dur: 13.13, line: "So needs versus wants is not a list you memorise. It is a question you ask \u2014 every time, just before the money leaves your hand.", stage: "avatar(point); banner(A QUESTION, NOT A LIST)" },
] };
