/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Price is not value", beats: [
    { dur: 7.17, line: "Two numbers hide inside everything you buy, and they are almost never the same.", stage: "avatar(talk); cols(Price,Value)" },
    { dur: 6.73, line: "The price is what the seller asks. It is printed, public, and real.", stage: "show(receipt); sort(receipt, a)" },
    { dur: 5.81, line: "The value is what the thing is worth to you \u2014 and only you can know it.", stage: "show(goal); sort(goal, b)" },
    { dur: 11.05, line: "Mags will sell you a shiny button for a whole week of wages. The price is real. The value is up to you.", stage: "avatar(point); show(chain); sort(chain, a); swap(chain)" },
    { dur: 8.81, line: "The gap between those two numbers is where every good decision lives \u2014 and every bad one too.", stage: "avatar(smile); banner(MIND THE GAP)" },
] };
