/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Gifts are not wages", beats: [
    { dur: 9.09, line: "Money you were given and money you earned spend exactly the same. But they are not the same to plan with.", stage: "avatar(talk); cols(Gift,Wage)" },
    { dur: 3.21, line: "A gift arrives once.", stage: "show(cake); sort(cake, a)" },
    { dur: 5.89, line: "A wage arrives again \u2014 as long as you keep doing the thing.", stage: "show(repeat); sort(repeat, b)" },
    { dur: 5.41, line: "A birthday five hundred is lovely. It is not an income.", stage: "avatar(point); show(coin); sort(coin, a)" },
    { dur: 6.45, line: "And a plan built on it falls over next month. Build your plan on what comes back.", stage: "avatar(talk); banner(BUILD ON WHAT COMES BACK)" },
] };
