/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "More than one tap", beats: [
    { dur: 7.33, line: "People who only have one way of getting money are one bad week away from having none.", stage: "avatar(talk); show(coin); weather(rain)" },
    { dur: 10.01, line: "Extra taps are everywhere. Selling something you no longer use. A second small job. Being paid for a thing you would do anyway.", stage: "cols(One tap,Many taps); show(cart); sort(cart, b); show(box); sort(box, b); show(broom); sort(broom, b)" },
    { dur: 4.81, line: "Mags sells buttons, mends umbrellas, and finds things.", stage: "avatar(point); show(umbrella); sort(umbrella, b)" },
    { dur: 6.05, line: "Two of those go badly most months. She is never broke.", stage: "weather(sun); banner(NEVER BROKE)" },
    { dur: 5.49, line: "One tap can be turned off. Three taps is a plan.", stage: "avatar(smile); banner(THREE TAPS IS A PLAN)" },
] };
