/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "The four jars", beats: [
    { dur: 6.69, line: "Here is the whole trick of managing money, and it happens in the first minute.", stage: "avatar(talk); show(jars)" },
    { dur: 13.85, line: "Split what comes in, the moment it arrives. Spend, for now. Save, for something soon. Grow, for far away. Give, for someone else.", stage: "cols(One pile,Four jars); show(coin); sort(coin, b); banner(SPLIT IT FIRST)" },
    { dur: 8.25, line: "Splitting first is everything \u2014 because anything left in one pile gets spent as one pile.", stage: "avatar(point); show(wallet); sort(wallet, a)" },
    { dur: 8.41, line: "I have done forty, thirty, twenty, ten for sixty years.", stage: "avatar(talk); banner(40 \u00b7 30 \u00b7 20 \u00b7 10)" },
    { dur: 4.21, line: "And I have never once made a spreadsheet.", stage: "avatar(smile)" },
] };
