/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "What it really cost", beats: [
    { dur: 8.37, line: "Every yes is also a no. That is the whole lesson, so I will say it again slowly.", stage: "avatar(talk); banner(EVERY YES IS A NO)" },
    { dur: 6.69, line: "Buying the shiny thing is not just minus six hundred.", stage: "show(chain); cols(You got,You gave up)" },
    { dur: 8.65, line: "It is also the trip you now cannot take. The goal that just moved three weeks further away.", stage: "sort(chain, a); show(goal); sort(goal, b); show(calendar); sort(calendar, b)" },
    { dur: 5.89, line: "Grown-ups call that opportunity cost. The second half of the price.", stage: "avatar(point); banner(OPPORTUNITY COST)" },
    { dur: 9.85, line: "Mags never mentions that half. That is not lying \u2014 it is just selling. Remembering it is your job.", stage: "avatar(smile)" },
] };
