/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "How many weeks?", beats: [
    { dur: 4.77, line: "A goal turns into a plan the moment you divide.", stage: "avatar(talk); show(goal)" },
    { dur: 8.97, line: "The skateboard is nine hundred. You save sixty a week. Nine hundred divided by sixty is fifteen.", stage: "banner(900 \u00f7 60 = 15 WEEKS); show(calendar)" },
    { dur: 5.89, line: "Not someday. Fifteen weeks. You can circle the day it lands.", stage: "avatar(point); banner(NOT SOMEDAY \u2014 FIFTEEN)" },
    { dur: 6.57, line: "If the answer is horrifying, you have exactly three honest choices.", stage: "avatar(talk); cols(Change the plan,Change the goal)" },
    { dur: 10.01, line: "Save more each week. Want something cheaper. Or wait longer. Everything else is just hoping.", stage: "show(coin); sort(coin, a); show(cart); sort(cart, b); banner(SAVE MORE \u00b7 CHEAPER \u00b7 WAIT)" },
] };
