/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Hurry is a tool", beats: [
    { dur: 6.61, line: "Today only. Last one. Ends at midnight.", stage: "avatar(talk); banner(TODAY ONLY!)" },
    { dur: 7.69, line: "Listen carefully: none of those are facts about the thing. They are tools that stop you thinking.", stage: "avatar(point); cols(About the thing,About YOU)" },
    { dur: 9.25, line: "A decision made fast feels like a decision made bravely. That is exactly what the hurry is for.", stage: "show(flame); sort(flame, b); banner(HURRY WORKS ON FEELINGS)" },
    { dur: 7.01, line: "Mags has said 'the last one' about the same tray of buttons for six years.", stage: "avatar(smile); show(chain); sort(chain, a)" },
    { dur: 9.57, line: "When you feel the rush, that is the moment to slow down. The cake shop will still be there tomorrow. So will the buttons.", stage: "avatar(talk); banner(SLOW IS THE MOVE)" },
] };
