/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Free is never free", beats: [
    { dur: 5.17, line: "If you are not paying money, something else is being paid.", stage: "avatar(talk); banner(SOMETHING IS BEING PAID)" },
    { dur: 8.77, line: "Your attention. Your details. Your time. Or a much bigger payment, later.", stage: "cols(You pay now,You pay later); show(gear); sort(gear, a); show(page); sort(page, a); show(coin); sort(coin, b)" },
    { dur: 7.69, line: "Free samples, free games, free trials \u2014 all real, and all paid for somehow.", stage: "avatar(point); show(game)" },
    { dur: 6.05, line: "The free trial that needs your card is not selling you a trial.", stage: "avatar(talk); show(receipt); sort(receipt, b)" },
    { dur: 7.25, line: "It is selling you the forgetting. Remember that, and free gets a lot cheaper.", stage: "avatar(smile); banner(IT SELLS THE FORGETTING)" },
] };
