/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "The small monthly one", beats: [
    { dur: 6.49, line: "A subscription is a decision you make once \u2014 and pay for forever.", stage: "avatar(talk); show(repeat); banner(DECIDE ONCE, PAY FOREVER)" },
    { dur: 7.69, line: "The small number is the point. Thirty a month does not feel like three hundred and sixty a year.", stage: "avatar(point); cols(Feels like,Actually is); show(coin); sort(coin, a); show(receipt); sort(receipt, b); banner(30/MONTH = 360/YEAR)" },
    { dur: 3.49, line: "But that is exactly what it is.", stage: "avatar(talk)" },
    { dur: 8.49, line: "Four small monthly things nobody remembers signing up for \u2014 that is most of a week of wages, every year.", stage: "show(page); show(game); show(bell); show(gear); sweep(b)" },
    { dur: 6.69, line: "Once a month, read the list. Cross one off. That is the whole defence.", stage: "avatar(smile); banner(READ THE LIST, CROSS ONE OFF)" },
] };
