/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "What a bank is for", beats: [
    { dur: 5.01, line: "A bank does three things a tin under the bed cannot.", stage: "avatar(talk); show(bank)" },
    { dur: 11.37, line: "It keeps money safer than any hiding place. It lets you pay without carrying notes. And it pays you a little, just for leaving money there.", stage: "cols(The tin,The bank); show(lock); sort(lock, b); show(coin); sort(coin, b)" },
    { dur: 8.01, line: "Why would a bank pay YOU? Because while your money sits, the bank lends it to somebody else.", stage: "avatar(point); show(deal); sort(deal, b); banner(YOUR MONEY GOES OUT WORKING)" },
    { dur: 4.85, line: "Your money does not sit in a drawer with your name on it.", stage: "avatar(talk)" },
    { dur: 6.77, line: "It is out working \u2014 and the bank owes you it back. Every coin.", stage: "avatar(smile); banner(THE BANK OWES YOU)" },
] };
