/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "The three secrets", beats: [
    { dur: 8.53, line: "Three things are yours and yours alone. A PIN. A password. A one-time code.", stage: "avatar(talk); show(lock); banner(PIN \u00b7 PASSWORD \u00b7 CODE)" },
    { dur: 6.05, line: "Now the strange part: nobody real ever needs them.", stage: "avatar(point); cols(Never asks,Might ask)" },
    { dur: 7.25, line: "Not the bank. Not the police. Not a helpful stranger. Not a friend.", stage: "show(bank); sort(bank, a); show(shield); sort(shield, a); show(family); sort(family, a)" },
    { dur: 5.69, line: "The real bank already knows your account. That is how it is your bank.", stage: "avatar(talk); banner(THE BANK ALREADY KNOWS)" },
    { dur: 7.93, line: "So anybody asking for a secret is telling you exactly what they are. Believe them.", stage: "avatar(smile); banner(ASKING = TELLING)" },
] };
