/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Telling someone is the answer", beats: [
    { dur: 6.29, line: "Here is why scams work on grown-ups too: embarrassment.", stage: "avatar(talk)" },
    { dur: 7.77, line: "The instruction 'don't tell anyone' is not protecting you. It is protecting them.", stage: "avatar(point); banner(WHO DOES THE SECRET PROTECT?)" },
    { dur: 8.69, line: "So telling somebody is not what you do after failing. Telling somebody IS the move.", stage: "show(family); banner(TELLING IS THE MOVE)" },
    { dur: 6.17, line: "A friend who really needs help can wait sixty seconds while you check with an adult.", stage: "avatar(talk); show(calendar)" },
    { dur: 5.25, line: "Someone who cannot wait sixty seconds \u2014 is not your friend.", stage: "avatar(smile); banner(SIXTY SECONDS)" },
] };
