/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Interest, both ways", beats: [
    { dur: 6.45, line: "Interest is rent \u2014 rent on money. And it runs both ways.", stage: "avatar(talk); banner(RENT ON MONEY)" },
    { dur: 5.17, line: "Leave money with a bank, and they pay you rent for using it.", stage: "cols(They pay you,You pay them); show(bank); show(coin); sort(coin, a)" },
    { dur: 4.57, line: "Borrow money, and you pay rent for using theirs.", stage: "show(receipt); sort(receipt, b)" },
    { dur: 5.61, line: "Same idea. Which side you stand on makes all the difference.", stage: "avatar(point); banner(SAME IDEA, TWO SIDES)" },
    { dur: 9.73, line: "Borrowing is not shameful. It is a tool with a price on it \u2014 and you always, always find the price before you agree.", stage: "avatar(smile); banner(FIND THE PRICE FIRST)" },
] };
