/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "The number that matters", beats: [
    { dur: 6.05, line: "Sellers quote the monthly payment, because the monthly payment is small.", stage: "avatar(talk); show(receipt); banner(ONLY 110 A MONTH!)" },
    { dur: 10.01, line: "The number that tells the truth is bigger and quieter: everything you will hand over, minus what you borrowed.", stage: "avatar(point); cols(You borrowed,You hand over)" },
    { dur: 6.89, line: "Borrow a thousand. Pay back one hundred and ten a month, for a year.", stage: "show(coin); sort(coin, a); show(calendar); sort(calendar, b)" },
    { dur: 5.69, line: "You handed over one thousand, three hundred and twenty.", stage: "banner(1,000 \u2192 1,320)" },
    { dur: 7.57, line: "It cost three hundred and twenty. THAT is the number. Ask for it by name.", stage: "avatar(smile); banner(IT COST 320)" },
] };
