/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Trust is a memory", beats: [
    { dur: 6.65, line: "Lenders keep a record of one thing only: whether people paid them back.", stage: "avatar(talk); show(page)" },
    { dur: 6.17, line: "A good record makes borrowing cheaper later. A bad one makes it dearer.", stage: "cols(Repaid,Didn't); show(tick); sort(tick, a); show(cross); sort(cross, b)" },
    { dur: 6.93, line: "Bizzington calls it a trust score. It goes up every time you repay.", stage: "avatar(point); show(medal); sort(medal, a); banner(UP EVERY REPAYMENT)" },
    { dur: 7.25, line: "It is a memory of what happened \u2014 not a score of what kind of person you are.", stage: "avatar(talk); banner(A MEMORY, NOT A JUDGEMENT)" },
    { dur: 6.05, line: "And a memory can be rebuilt. One repayment at a time.", stage: "avatar(smile)" },
] };
