/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "The snowball", beats: [
    { dur: 4.09, line: "Interest lands on your money. You know that part.", stage: "avatar(talk); show(coin)" },
    { dur: 8.73, line: "Here is the part that changes everything: next time, it lands on your money PLUS the interest.", stage: "avatar(point); banner(INTEREST ON THE INTEREST)" },
    { dur: 11.93, line: "One hundred, growing ten percent a year. One hundred and ten. Then one hundred and twenty-one. Then one hundred and thirty-three.", stage: "cols(Year,You have); show(seed); sort(seed, a); show(chart); sort(chart, b); banner(110 \u2192 121 \u2192 133)" },
    { dur: 6.81, line: "The steps get bigger while you do nothing at all. That is compounding.", stage: "avatar(talk); banner(THE STEPS GET BIGGER)" },
    { dur: 6.09, line: "It is boring for a year. And then it is not boring at all.", stage: "avatar(smile)" },
] };
