/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Risk and return", beats: [
    { dur: 5.01, line: "Things that might grow a lot can also fall a lot.", stage: "avatar(talk); cols(Might grow,Might fall); show(chart); sort(chart, a); show(chartdown); sort(chartdown, b)" },
    { dur: 6.97, line: "Hear it properly: that is one sentence, not two. The same sentence.", stage: "avatar(point); banner(THE SAME SENTENCE)" },
    { dur: 5.41, line: "Safe things grow slowly. That is their half of the deal.", stage: "show(shield); show(seed)" },
    { dur: 8.49, line: "Bo says it will go up. Bea says it will go down. Neither of them knows \u2014 and both of them are certain.", stage: "avatar(talk); swap(chart)" },
    { dur: 10.49, line: "So when somebody promises big returns with no risk, they are either confused or lying. There is no third kind.", stage: "avatar(smile); banner(NO THIRD KIND)" },
] };
