/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Never just one", beats: [
    { dur: 6.65, line: "Own one thing, and your whole week depends on somebody else's Tuesday.", stage: "avatar(talk); show(factory); weather(rain)" },
    { dur: 6.69, line: "Own a slice of many things, and no single piece of bad news can wreck you.", stage: "avatar(point); cols(Just one,A slice of many); show(factory); sort(factory, a); show(basket); sort(basket, b); weather(sun)" },
    { dur: 3.85, line: "A basket of the whole market is dull.", stage: "show(cart); sort(cart, b); banner(DULL)" },
    { dur: 4.45, line: "And dull wins more often than exciting does.", stage: "avatar(smile); banner(DULL WINS)" },
    { dur: 7.13, line: "Spreading out is the only free thing in this entire subject. Take it.", stage: "avatar(talk); banner(THE ONLY FREE THING)" },
] };
