/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Time is the ingredient", beats: [
    { dur: 6.69, line: "Where money should live depends on one question: when will you need it back?", stage: "avatar(talk); banner(WHEN DO YOU NEED IT?)" },
    { dur: 8.57, line: "Money you need next month must sit somewhere safe \u2014 even if it grows by almost nothing.", stage: "cols(Next month,Ten years); show(shield); sort(shield, a)" },
    { dur: 9.93, line: "Money you will not touch for ten years can sit through bad weather. It has time to come back.", stage: "avatar(point); show(seed); sort(seed, b); weather(rain)" },
    { dur: 5.65, line: "The bus fare and the retirement fund are not the same money.", stage: "weather(sun); show(runner); sort(runner, a); show(chart); sort(chart, b)" },
    { dur: 4.49, line: "And they must not live in the same place.", stage: "avatar(smile); banner(DIFFERENT MONEY, DIFFERENT HOMES)" },
] };
