/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Setting a price", beats: [
    { dur: 5.09, line: "Price too low, and you sell out by lunch and earn nothing.", stage: "avatar(talk); cols(Too low,Too high); show(cart); sort(cart, a)" },
    { dur: 4.77, line: "Price too high, and you carry the stock home again.", stage: "show(box); sort(box, b)" },
    { dur: 7.85, line: "The right price is not 'cost plus a bit'. It is the most people will happily pay.", stage: "avatar(point); banner(WHAT PEOPLE HAPPILY PAY)" },
    { dur: 9.69, line: "And you only find it by trying. Mags raised her buttons from eight to twelve \u2014 and sold two fewer.", stage: "show(chain); banner(8 \u2192 12, TWO FEWER SOLD)" },
    { dur: 6.89, line: "She made more money and went home earlier. Try prices like a scientist.", stage: "avatar(smile); banner(TRY IT LIKE A SCIENTIST)" },
] };
