/* generated by tools/lessons/process-all.py — do not edit. */
export default { title: "Cash is not profit", beats: [
    { dur: 9.61, line: "Here is the strangest true thing in this whole chapter: you can be profitable and broke at the same time.", stage: "avatar(talk); banner(PROFITABLE AND BROKE)" },
    { dur: 5.33, line: "Profit lives on paper, over a month.", stage: "cols(On paper,In your hand); show(page); sort(page, a)" },
    { dur: 9.41, line: "Cash is what is actually in your hand on Tuesday \u2014 when the stock must be paid for and the customers have not come yet.", stage: "avatar(point); show(coin); sort(coin, b); show(calendar); sort(calendar, b)" },
    { dur: 8.49, line: "My best-ever month nearly closed the shop. The restock was due before the sales landed.", stage: "weather(rain); banner(THE RESTOCK CAME FIRST)" },
    { dur: 6.17, line: "Watch the paper once a month. Watch your hand every day.", stage: "avatar(smile); weather(sun); banner(WATCH YOUR HAND DAILY)" },
] };
