"""process-all.py — assemble every recorded lesson into per-lesson modules.

Weight is the whole reason this file exists. Thirty-two narrated lessons are
about five megabytes of audio, and one module holding all of it would ride
in the main bundle of an app whose first paint budget is measured in
milliseconds. So:

  app/src/lessons/<id>.js       the lesson, audio embedded
  app/src/lessons/<id>.lite.js  the same lesson, audio stripped — captions
                                and measured durations still carry the
                                teaching, on the duration clock
  app/src/lessons-poses.js      the teaching avatars, shared once
  app/src/lessonindex-list.js   loaders, every lesson FULL (Vite splits each
                                dynamic import into its own cached chunk)
  app/src/lessonindex-lite.js   loaders, chapter 1 full and the rest lite —
                                what the single self-contained file inlines,
                                because a 7 MB "one file" stops being a
                                courtesy

A lesson only ships if its run VERIFIED: every clip present, measured, loud
enough. An unverified run is skipped loudly, never promoted quietly.
"""
import base64, importlib.util, io, json, os, sys, glob
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, '..', 'art')
APP = os.path.join(HERE, '..', '..', 'app', 'src')
OUTDIR = os.path.join(APP, 'lessons')
os.makedirs(OUTDIR, exist_ok=True)
spec = importlib.util.spec_from_file_location('pi', os.path.join(ART, 'process-icons.py'))
pi = importlib.util.module_from_spec(spec); spec.loader.exec_module(pi)
from scripts import LESSONS

HEAD = "/* generated by tools/lessons/process-all.py — do not edit. */\n"

# ── poses, shared once ──────────────────────────────────────────────────
poses = {}
for f in sorted(glob.glob(os.path.join(ART, 'nana-*.png'))):
    name = os.path.basename(f)[5:-4]
    im = Image.open(f); im = im.crop(pi.content_box(im)); im = pi.dealpha(im, tol=46)
    a = im.getchannel('A'); w0, h0 = im.size; px = a.load()
    cols = [sum(1 for y in range(0, h0, 2) if px[x, y] > 12) for x in range(w0)]
    rows = [sum(1 for y in range(0, w0, 2) if px[y, x] > 12) for x in range(h0)]
    xs = [i for i, v in enumerate(cols) if v >= 4]; ys = [i for i, v in enumerate(rows) if v >= 4]
    if xs and ys: im = im.crop((max(0, xs[0]-2), max(0, ys[0]-2), min(w0, xs[-1]+3), min(h0, ys[-1]+3)))
    r = 300 / im.height
    im = im.resize((max(1, round(im.width * r)), 300), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=82, method=6)
    poses[name] = (im.width, im.height, base64.b64encode(buf.getvalue()).decode())
with open(os.path.join(APP, 'lessons-poses.js'), 'w') as o:
    o.write(HEAD + "/* Nana Bizz's teaching poses — the cast are animals, and the teacher is\n   the tortoise, exactly as her portrait draws her. */\nexport const POSES = {\n")
    for name, (w, h, data) in poses.items():
        o.write(f"  '{name}': {{ w: {w}, h: {h}, src: 'data:image/webp;base64,{data}' }},\n")
    o.write('};\n')
print(f'poses: {len(poses)}')

# ── lessons ─────────────────────────────────────────────────────────────
ready, skipped = [], []
for lid, L in LESSONS.items():
    run = os.path.join(HERE, f'run-{lid}')
    mf = os.path.join(run, 'manifest.json')
    if not os.path.exists(mf): skipped.append(lid); continue
    man = json.load(open(mf))
    if len(man) != len(L['beats']) or any(m['dur'] < 0.9 or m['db'] < -40 for m in man):
        skipped.append(lid + ' (NOT CLEAN)'); continue
    full, lite = [], []
    for m in man:
        mp3 = open(os.path.join(run, f'{lid}-{m["i"]}.mp3'), 'rb').read()
        core = f"dur: {m['dur']}, line: {json.dumps(m['line'])}, stage: {json.dumps(m['stage'])}"
        full.append(f"    {{ {core}, src: 'data:audio/mpeg;base64,{base64.b64encode(mp3).decode()}' }},")
        lite.append(f"    {{ {core} }},")
    for suffix, beats in (('', full), ('.lite', lite)):
        with open(os.path.join(OUTDIR, f'{lid}{suffix}.js'), 'w') as o:
            o.write(HEAD + f"export default {{ title: {json.dumps(L['title'])}, beats: [\n" + '\n'.join(beats) + '\n] };\n')
    ready.append(lid)
print(f'lessons: {len(ready)} ready, skipped: {skipped or "none"}')

# ── the two loader lists ────────────────────────────────────────────────
with open(os.path.join(APP, 'lessonindex-list.js'), 'w') as o:
    o.write(HEAD + "/* every lesson full — Vite gives each dynamic import its own chunk,\n   fetched on first watch and then held by the service worker */\nexport const LOADERS = {\n")
    for lid in ready:
        o.write(f"  '{lid}': () => import('./lessons/{lid}.js'),\n")
    o.write('};\n')
with open(os.path.join(APP, 'lessonindex-lite.js'), 'w') as o:
    o.write(HEAD + "/* the single-file variant: chapter 1 speaks, the rest teach in captions\n   on the measured-duration clock — a 7 MB \"one file\" is no courtesy */\nexport const LOADERS = {\n")
    for lid in ready:
        suffix = '' if lid.startswith('c1') else '.lite'
        o.write(f"  '{lid}': () => import('./lessons/{lid}{suffix}.js'),\n")
    o.write('};\n')
total = sum(os.path.getsize(os.path.join(OUTDIR, f)) for f in os.listdir(OUTDIR))
print(f'lessons/: {total // 1024} kB across {len(os.listdir(OUTDIR))} modules')
