"""process-all.py — assemble every recorded lesson.

AUDIO IS FILES, REFERENCED BY KEY. This is the family's answer, and both
siblings prove it at a scale this app will never reach: Bizzing Bee ships
42,392 mp3 clips (1.2 GB), Bizzing India 11,506 (522 MB) — every one a loose
file under voice/, addressed by key, cached by the service worker like any
other same-origin GET. India's bhasha.js states the rule outright: "Audio is
referenced BY KEY only — 'hi/ka' means voice/hi/ka.mp3."

The first cut of this file embedded clips as base64 data URIs inside the
JavaScript. That was wrong three ways and the siblings had already paid for
each: base64 costs a third of the bytes for nothing; the browser cannot
cache a clip independently of the code around it; and audio inside a module
is audio the parser must walk before the app can paint.

So:
  app/public/voice/lessons/<id>-<n>.mp3   the clips, as files
  app/src/lessons/<id>.js                 beats: dur, line, stage, key
  app/src/lessons-poses.js                the teaching avatars, shared once
  app/src/lessonindex-list.js             loaders (Vite chunks each one)
  app/src/lessonindex-lite.js             the same beats with no keys — the
                                          single self-contained file has no
                                          server to fetch a clip FROM, so it
                                          teaches in captions on the measured
                                          duration clock

A lesson only ships if its run VERIFIED: every clip present, measured, loud
enough. An unverified run is skipped loudly, never promoted quietly.
"""
import base64, importlib.util, io, json, os, shutil, sys, glob
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, '..', 'art')
APP = os.path.join(HERE, '..', '..', 'app', 'src')
OUTDIR = os.path.join(APP, 'lessons')
VOICE = os.path.join(APP, '..', 'public', 'voice', 'lessons')
os.makedirs(OUTDIR, exist_ok=True)
os.makedirs(VOICE, exist_ok=True)
spec = importlib.util.spec_from_file_location('pi', os.path.join(ART, 'process-icons.py'))
pi = importlib.util.module_from_spec(spec); spec.loader.exec_module(pi)
from scripts import LESSONS

HEAD = "/* generated by tools/lessons/process-all.py — do not edit. */\n"

# ── poses, shared once ──────────────────────────────────────────────────
poses = {}
for f in sorted(glob.glob(os.path.join(ART, 'nana-*.png'))):
    name = os.path.basename(f)[5:-4]
    im = Image.open(f); im = im.crop(pi.content_box(im)); im = pi.dealpha(im, tol=46)
    a = im.getchannel('A'); w0, h0 = im.size; px = a.load()
    cols = [sum(1 for y in range(0, h0, 2) if px[x, y] > 12) for x in range(w0)]
    rows = [sum(1 for y in range(0, w0, 2) if px[y, x] > 12) for x in range(h0)]
    xs = [i for i, v in enumerate(cols) if v >= 4]; ys = [i for i, v in enumerate(rows) if v >= 4]
    if xs and ys: im = im.crop((max(0, xs[0]-2), max(0, ys[0]-2), min(w0, xs[-1]+3), min(h0, ys[-1]+3)))
    r = 300 / im.height
    im = im.resize((max(1, round(im.width * r)), 300), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=82, method=6)
    poses[name] = (im.width, im.height, base64.b64encode(buf.getvalue()).decode())
with open(os.path.join(APP, 'lessons-poses.js'), 'w') as o:
    o.write(HEAD + "/* Nana Bizz's teaching poses — the cast are animals, and the teacher is\n   the tortoise, exactly as her portrait draws her. */\nexport const POSES = {\n")
    for name, (w, h, data) in poses.items():
        o.write(f"  '{name}': {{ w: {w}, h: {h}, src: 'data:image/webp;base64,{data}' }},\n")
    o.write('};\n')
print(f'poses: {len(poses)}')

# ── lessons ─────────────────────────────────────────────────────────────
ready, skipped = [], []
for lid, L in LESSONS.items():
    run = os.path.join(HERE, f'run-{lid}')
    mf = os.path.join(run, 'manifest.json')
    if not os.path.exists(mf): skipped.append(lid); continue
    man = json.load(open(mf))
    if len(man) != len(L['beats']) or any(m['dur'] < 0.9 or m['db'] < -40 for m in man):
        skipped.append(lid + ' (NOT CLEAN)'); continue
    full, lite = [], []
    for m in man:
        name = f'{lid}-{m["i"]}.mp3'
        shutil.copyfile(os.path.join(run, name), os.path.join(VOICE, name))
        core = f"dur: {m['dur']}, line: {json.dumps(m['line'])}, stage: {json.dumps(m['stage'])}"
        full.append(f"    {{ {core}, key: '{lid}-{m['i']}' }},")
        lite.append(f"    {{ {core} }},")
    for suffix, beats in (('', full), ('.lite', lite)):
        with open(os.path.join(OUTDIR, f'{lid}{suffix}.js'), 'w') as o:
            o.write(HEAD + f"export default {{ title: {json.dumps(L['title'])}, beats: [\n" + '\n'.join(beats) + '\n] };\n')
    ready.append(lid)
print(f'lessons: {len(ready)} ready, skipped: {skipped or "none"}')

# ── the two loader lists ────────────────────────────────────────────────
with open(os.path.join(APP, 'lessonindex-list.js'), 'w') as o:
    o.write(HEAD + "/* every lesson, with its clip keys — the module is a few hundred bytes\n   and the audio is fetched per clip from voice/lessons/, cached by the\n   worker like anything else same-origin */\nexport const LOADERS = {\n")
    for lid in ready:
        o.write(f"  '{lid}': () => import('./lessons/{lid}.js'),\n")
    o.write('};\n')
with open(os.path.join(APP, 'lessonindex-lite.js'), 'w') as o:
    o.write(HEAD + "/* the single-file variant: one HTML file has no server to fetch a clip\n   from, so every lesson teaches in captions on the measured-duration\n   clock. The narration lives on the web build. */\nexport const LOADERS = {\n")
    for lid in ready:
        suffix = '.lite'
        o.write(f"  '{lid}': () => import('./lessons/{lid}{suffix}.js'),\n")
    o.write('};\n')
mods = sum(os.path.getsize(os.path.join(OUTDIR, f)) for f in os.listdir(OUTDIR))
clips = [f for f in os.listdir(VOICE) if f.endswith('.mp3')]
audio = sum(os.path.getsize(os.path.join(VOICE, f)) for f in clips)
print(f'src/lessons/: {mods // 1024} kB of modules across {len(os.listdir(OUTDIR))} files')
print(f'public/voice/lessons/: {len(clips)} clips, {audio // 1024} kB — files, not data URIs')
