/* content-extra.js — the second and third questions for every chapter card.

   One question per card was an attention check; three make a real drill.
   The rules every entry keeps (the same ones objectives.js enforces on the
   retrieval items):

   · the answer is NEVER in the question's own words — no option quotes the
     teach text back so exactly that recognition beats understanding
   · distractors are the card's real misconceptions, not filler: the wrong
     answers are what a child who half-learnt it would actually say
   · options are similar in length, because length is a leak
   · position is permuted per question from the card id (shuffledDrill
     seeds on id + question index), because position is a leak too
   · numbers come from the card. Nothing is invented here.

   Keyed by card id; content.js merges these in as card.qs. */

export const EXTRA_QS = {
  c1a: [
    { q: 'Why does a shopkeeper accept a paper note for real bread?',
      opts: ['The paper is worth a lot itself', 'Everyone has agreed the note counts', 'The bank forces every shop to', 'Bread is cheap to make anyway'], a: 1,
      why: 'The paper is nearly worthless. The agreement is the money.' },
    { q: 'You cross a border and your notes stop working. What actually changed?',
      opts: ['Your notes wore out', 'The place agrees on different money', 'Bread costs more there', 'Your notes were fakes'], a: 1,
      why: 'Different places, different agreements. The notes are the same paper they were yesterday.' },
  ],
  c1b: [
    { q: 'Winter is coming and your only jumper has worn through. The new jumper is…',
      opts: ['A want, clothes are optional', 'A need, this season at least', 'A waste of good money', 'A need only if it is cheap'], a: 1,
      why: 'Cold is trouble. The same jumper in a hot dry June would sit in the other column.' },
    { q: 'What makes something a want rather than a need?',
      opts: ['It costs more than a need', 'Life is nicer with it, fine without it', 'It is bought in a hurry', 'Grown-ups would not buy it'], a: 1,
      why: 'Price has nothing to do with it — a cheap sticker is a want and a dear medicine is a need.' },
  ],
  c1c: [
    { q: 'The grain seller pays Pip to carry crates. Why is the seller happy too?',
      opts: ['He got time he did not have', 'He got rid of spare coins', 'Carrying is fun to watch', 'He owed Pip a favour'], a: 0,
      why: 'A trade both sides walk away happier from — that is where money comes from.' },
    { q: 'A message says you will be given money for nothing. What does chapter five say it is?',
      opts: ['A prize you were lucky to win', 'A trick, because pay is a trade', 'A gift from a kind stranger', 'A bank being generous'], a: 1,
      why: 'Nobody is given money for nothing. A message promising it has a different plan for yours.' },
  ],
  c1d: [
    { q: 'The same button: Mags asks 12, you would happily pay 5. Which number is the value?',
      opts: ['12, the seller sets it', '5, what it is worth to you', 'The average of the two', 'Whatever it cost to make'], a: 1,
      why: 'Price is the ask. Value is yours to judge, and only you can judge it.' },
    { q: 'When is paying MORE than the price tag still a good deal?',
      opts: ['Never, the tag is the truth', 'When its value to you is higher still', 'When the seller seems friendly', 'When you can pay it monthly'], a: 1,
      why: 'The whole game is the gap between price and value — in your favour.' },
  ],
  c2a: [
    { q: 'Two hours of crate-stacking felt endless today. What does it pay?',
      opts: ['Less, tired work is sloppy', 'The same, the hours are the product', 'More, hard days earn extra', 'It depends on your mood'], a: 1,
      why: 'You sold two hours. How they felt was never on the price tag.' },
    { q: 'Why does anyone pay someone else to do a job at all?',
      opts: ['They have money but not time', 'They cannot do anything themselves', 'They enjoy giving money away', 'The law says work must be paid'], a: 0,
      why: 'The trade underneath nearly every job: their money for your time.' },
  ],
  c2b: [
    { q: 'Nana rehired the same boy for eleven years. What was he best at?',
      opts: ['Being the fastest with crates', 'Saying when something went wrong', 'Working for the lowest pay', 'Making the funniest jokes'], a: 1,
      why: 'He always said when a crate was cracked. Trust rehires; speed just finishes early.' },
    { q: 'Where does the second job come from?',
      opts: ['Luck, the same as the first', 'How you did the first one', 'Asking twice as many people', 'Lowering what you charge'], a: 1,
      why: 'The first is luck. Every one after that is your record walking ahead of you.' },
  ],
  c2c: [
    { q: 'A birthday 500 and a wage of 500 — what is the planning difference?',
      opts: ['None, money is money', 'The wage returns, the gift will not', 'Gifts must be spent on fun', 'Wages are taxed, gifts are not'], a: 1,
      why: 'They spend the same. Only one of them arrives again next month.' },
    { q: 'A plan built on birthday money falls over. When?',
      opts: ['Immediately, gifts do not count', 'Next month, when nothing arrives', 'Only if the gift was small', 'When the giver finds out'], a: 1,
      why: 'A gift arrives once. The plan needed it to arrive again, and it will not.' },
  ],
  c2d: [
    { q: 'Mags has three ways money comes in and two go badly most months. Why is she never broke?',
      opts: ['The third tap is still running', 'She saves her whole income', 'Buttons are always in fashion', 'She borrows when short'], a: 0,
      why: 'Three taps. Some months only one runs — one is enough to not be broke.' },
    { q: 'Which of these is an extra tap?',
      opts: ['Selling a bike you outgrew', 'Wishing for a bigger wage', 'Spending a little less', 'Keeping money in a safer tin'], a: 0,
      why: 'Spending less helps, but a tap is money coming IN — a sale, a second job, a paid hobby.' },
  ],
  c3a: [
    { q: 'In is 200. Out is 100. Which number do you actually get to choose about?',
      opts: ['The 200 coming in', 'The 100 left over', 'The rent inside the out', 'None, budgets are fixed'], a: 1,
      why: 'In is set by your work; much of out is bills. The leftover is where the choosing lives.' },
    { q: 'Out has grown bigger than in. Where does the difference come from?',
      opts: ['Nowhere, it cancels out', 'Savings, or someone else', 'The shop just waits kindly', 'It becomes small change'], a: 1,
      why: 'Spending above income is never free — it drains savings or becomes borrowing.' },
  ],
  c3b: [
    { q: 'Why split money into jars the moment it arrives, not later?',
      opts: ['Jars look tidier on a shelf', 'One pile gets spent as one pile', 'Banks require four accounts', 'Coins rust if left together'], a: 1,
      why: 'Split first, or the pile quietly becomes all-Spend. That is the whole trick.' },
    { q: 'In 40/30/20/10, what is the 10 for?',
      opts: ['Emergencies only', 'Someone other than you', 'Sweets and small treats', 'Paying back the bank'], a: 1,
      why: 'Spend, Save, Grow — and Give: the jar for someone else.' },
  ],
  c3c: [
    { q: 'The shiny thing costs 600. What is the SECOND half of its price?',
      opts: ['The goal that moved further away', 'The tax on top of it', 'The bag it comes in', 'The time spent shopping'], a: 0,
      why: 'Every yes is a no. The trip not taken and the goal pushed back are real costs with no receipt.' },
    { q: 'Why does Mags never mention opportunity cost?',
      opts: ['She has never heard of it', 'Selling means showing one half only', 'It is rude to discuss money', 'It does not apply to buttons'], a: 1,
      why: 'Not lying — selling. Remembering the second half of the price is the buyer’s job. Yours.' },
  ],
  c3d: [
    { q: 'The answer to price ÷ weekly saving is horrifying. Which is NOT one of your three honest choices?',
      opts: ['Save more every week', 'Hope the price drops soon', 'Want something cheaper', 'Wait more weeks'], a: 1,
      why: 'Hoping is the dishonest fourth option. More in, cheaper target, or longer — those are the three.' },
    { q: 'What does dividing price by weekly saving actually turn a wish into?',
      opts: ['A date you can circle', 'A smaller price', 'A reason to borrow', 'A disappointment'], a: 0,
      why: '"Someday" becomes "fifteen weeks". A number you can circle is a plan.' },
  ],
  c4a: [
    { q: '"Ends at midnight!" is information about…',
      opts: ['The thing being sold', 'Your thinking time', 'The shop’s closing hours', 'The price after midnight'], a: 1,
      why: 'Hurry is aimed at the buyer, not the product. It exists to shrink your thinking.' },
    { q: 'Mags has called the same tray "the last one" for six years. What should that teach you?',
      opts: ['Her stock is nearly gone', 'Scarcity talk is a sales tool', 'Buttons sell out quickly', 'She has a bad memory'], a: 1,
      why: '"Last one" was never a fact about the tray. It is a lever, and now you can see it.' },
  ],
  c4b: [
    { q: 'A game is free to play. Who is probably paying for it?',
      opts: ['Nobody, some things are free', 'You, with attention or details', 'The phone company', 'Other richer players only'], a: 1,
      why: 'If money is not leaving you, something else is: attention, details, time, or a later payment.' },
    { q: 'Why does a free trial want your card number?',
      opts: ['To check you are a real person', 'To charge you when you forget', 'Cards make sign-up faster', 'The law requires it'], a: 1,
      why: 'It is not selling the trial. It is selling the forgetting.' },
  ],
  c4c: [
    { q: '30 a month is how much a year?',
      opts: ['300', '360', '330', '390'], a: 1,
      why: 'Twelve months of 30. The small number is the disguise; the year number is the truth.' },
    { q: 'Why are subscriptions priced monthly instead of yearly?',
      opts: ['Monthly maths is easier', 'Small numbers slip past you', 'Banks prefer twelve payments', 'Yearly prices are illegal'], a: 1,
      why: '30 feels like pocket change. 360 would make you stop and think — which is why you never see it.' },
  ],
  c4d: [
    { q: 'Why is the milk at the very back of the shop?',
      opts: ['It stays colder back there', 'You pass everything to reach it', 'Delivery doors are at the back', 'Nobody buys milk anyway'], a: 1,
      why: 'Eleven temptations stand between the door and the milk, and each one was placed.' },
    { q: 'What is the defence against a shop built as a machine?',
      opts: ['Only ever shop online', 'A list, written before you enter', 'Shopping as fast as you can', 'Never carrying any money'], a: 1,
      why: 'The machine is very good, but it cannot read your list.' },
  ],
  c5a: [
    { q: 'Where is the money you put in a bank, most of the time?',
      opts: ['In a drawer with your name', 'Lent out, working elsewhere', 'Stacked in the big vault', 'Changed into gold bars'], a: 1,
      why: 'It is out working — and the bank owes you every coin of it back.' },
    { q: 'Why does the bank pay YOU for keeping money there?',
      opts: ['To be polite to customers', 'It earns by lending your money on', 'The government makes it', 'It only pays rich people'], a: 1,
      why: 'While your money sits, the bank lends it to someone else and shares a sliver with you.' },
  ],
  c5b: [
    { q: 'A caller says they are your bank and asks for the one-time code. Who are they?',
      opts: ['The bank, doing a check', 'A scammer, by definition', 'The phone company', 'Impossible to tell'], a: 1,
      why: 'Nobody real needs your secrets. Asking is confessing.' },
    { q: 'Why does your real bank never ask for your PIN?',
      opts: ['It already runs your account', 'PINs change too often', 'Asking is bad manners', 'It uses fingerprints instead'], a: 0,
      why: 'The real bank does not need your secrets to see your account — that is what makes it your bank.' },
  ],
  c5c: [
    { q: 'Prize draw, panicked "account at risk", friend stuck abroad. What do all three share?',
      opts: ['They involve big money', 'Hurry plus a secret', 'They come by phone', 'They target children'], a: 1,
      why: 'Different stories, one shape: bait, hurry, secrecy. See the shape and the story stops mattering.' },
    { q: 'Why do scams always include "reply within 2 hours"?',
      opts: ['The offer really expires', 'Thinking time kills scams', 'Servers close at midnight', 'It sounds professional'], a: 1,
      why: 'A scam survives exactly as long as you do not stop to think. The clock is aimed at your thinking.' },
  ],
  c5d: [
    { q: '"Don’t tell anyone" is protecting…',
      opts: ['You, from embarrassment', 'The scammer, from discovery', 'Your family, from worry', 'The prize, from thieves'], a: 1,
      why: 'Secrecy is the scam’s armour. One sentence to an adult and it dies.' },
    { q: 'A real friend in real trouble asks for money RIGHT NOW. What can they always survive?',
      opts: ['Sixty seconds while you check', 'Being told no outright', 'You telling everyone', 'A smaller amount'], a: 0,
      why: 'Real trouble survives a sixty-second check with an adult. Fake trouble cannot afford it.' },
  ],
  c6a: [
    { q: 'Interest is best described as…',
      opts: ['A fine for being poor', 'Rent paid on money', 'A tip for the bank', 'A tax on savings'], a: 1,
      why: 'Rent on money, running both ways: they rent yours, you rent theirs.' },
    { q: 'What must you ALWAYS do before agreeing to borrow?',
      opts: ['Find the full price of it', 'Feel ashamed about it', 'Ask two banks at least', 'Wait a whole week'], a: 0,
      why: 'Borrowing is a tool with a price. Find the price first — always.' },
  ],
  c6b: [
    { q: 'Why do sellers quote the monthly payment instead of the total?',
      opts: ['Monthly is the legal format', 'Small numbers hide the cost', 'Totals are hard to compute', 'Banks set the rules'], a: 1,
      why: '110 a month sounds gentle. 1,320 handed over for 1,000 borrowed — 320 of cost — does not.' },
    { q: 'Borrow 1,000 and hand over 1,320 in total. What did the loan cost?',
      opts: ['1,320', '320', '1,000', '110'], a: 1,
      why: 'Everything handed over, minus what you borrowed. That gap is the price of the loan.' },
  ],
  c6c: [
    { q: 'Which of these is borrowing for a thing that is "gone by Friday"?',
      opts: ['A feast for the festival', 'A stall roof repair', 'A crate-carrying trolley', 'A bread-baking course'], a: 0,
      why: 'The roof, the trolley and the course all last or earn. The feast is a memory paying rent.' },
    { q: 'Nana borrowed for umbrella stock AND for the festival. What did she say about the festival loan?',
      opts: ['She regrets it bitterly', 'She would do it again, knowingly', 'It was her best investment', 'The bank forgave it'], a: 1,
      why: 'It made no money and she would do it again — the point is doing it knowingly.' },
  ],
  c6d: [
    { q: 'What does a trust score actually record?',
      opts: ['What kind of person you are', 'Whether you repaid your loans', 'How much money you keep saved', 'How often you visit the bank'], a: 1,
      why: 'A memory of what happened — never a judgement of who you are.' },
    { q: 'Your record has some bad marks. What does the card say about that?',
      opts: ['It follows you forever', 'Repaying rebuilds it over time', 'You must change banks now', 'Only cash from here on'], a: 1,
      why: 'The memory can be rebuilt — up every time you repay, and it never says anything about you.' },
  ],
  c7a: [
    { q: '100 grows 10% a year. Why is year three’s step bigger than year one’s?',
      opts: ['Banks raise rates yearly', 'Interest now lands on interest too', 'Prices rose meanwhile', 'It is not — steps are equal'], a: 1,
      why: '110, 121, 133 — each step lands on everything before it. That is compounding.' },
    { q: 'What do YOU have to do while compounding works?',
      opts: ['Nothing at all', 'Add money every week', 'Move banks yearly', 'Check it every day'], a: 0,
      why: 'The steps get bigger while you do nothing. Boring for a year — then not boring at all.' },
  ],
  c7b: [
    { q: '"Might grow a lot" and "might fall a lot" are…',
      opts: ['Two different investments', 'The same sentence about one thing', 'A safe one and a risky one', 'Bo’s view versus Bea’s'], a: 1,
      why: 'One sentence, not two. Big possible up IS big possible down.' },
    { q: 'Someone promises big returns with NO risk. The card says they are…',
      opts: ['Confused or lying', 'Probably a genius', 'A very lucky investor', 'A bank in disguise'], a: 0,
      why: 'There is no third kind. Safe grows slowly; anything promising otherwise is broken somewhere.' },
  ],
  c7c: [
    { q: 'Owning shares in one single company means…',
      opts: ['Bigger guaranteed returns', 'Your week rides on their Tuesday', 'Lower fees than baskets', 'You control the company'], a: 1,
      why: 'One piece of bad news, and it is your news. A slice of many things shrugs it off.' },
    { q: 'Why does the card call spreading out "the only free thing in this subject"?',
      opts: ['Baskets charge no fees', 'Less wreck-risk without less return', 'Banks give baskets away', 'Dull things cost nothing'], a: 1,
      why: 'Diversifying cuts the chance of ruin without costing you the growth. Nothing else in finance is free.' },
  ],
  c7d: [
    { q: 'Money you need next month belongs…',
      opts: ['Wherever it grows fastest', 'Somewhere safe, even if it barely grows', 'Split across many shares', 'With the ten-year money'], a: 1,
      why: 'Next-month money cannot sit through a storm. Safety is its job; growth is not.' },
    { q: 'Why can ten-year money ride out a bad year?',
      opts: ['It has time to come back', 'Bad years refund later', 'Banks protect old money', 'It cannot — sell at once'], a: 0,
      why: 'Time is the ingredient: what falls has years to recover before you need it.' },
  ],
  c8a: [
    { q: '800 came in, the stock cost 320. The 480 is…',
      opts: ['Revenue', 'Profit', 'Cost', 'Cash flow'], a: 1,
      why: 'Revenue in, cost out, profit is what is left. Three words, never mixed.' },
    { q: 'A shop is packed all day but profit is zero. What is it?',
      opts: ['A thriving business', 'A very tiring hobby', 'About to be rich', 'Impossible to happen'], a: 1,
      why: 'Busy is revenue’s friend, not profit’s. No leftover, no business.' },
  ],
  c8b: [
    { q: 'Mags raised buttons from 8 to 12 and sold two fewer. Result?',
      opts: ['More money, home earlier', 'Less money overall', 'Exactly the same takings', 'She lost her customers'], a: 0,
      why: 'Fewer sales at a better price beat more sales at a poor one — you find this only by trying.' },
    { q: 'You price so low you sell out by lunch. What did the card call that?',
      opts: ['A triumph of marketing', 'Earning nothing while busy', 'Perfect stock control', 'The scientific method'], a: 1,
      why: 'Sold out fast usually means priced too low: all the work, none of the profit.' },
  ],
  c8c: [
    { q: 'Profitable on paper, no cash on Tuesday. What happened?',
      opts: ['The bookkeeping is wrong', 'Bills came before the sales landed', 'Profit was stolen', 'It cannot happen'], a: 1,
      why: 'Nana’s best month nearly closed the shop: the restock was due first. Timing is the trap.' },
    { q: 'How often do you watch cash versus profit?',
      opts: ['Both monthly is fine', 'Cash daily, paper monthly', 'Profit daily, cash monthly', 'Only at year end'], a: 1,
      why: 'Profit is a monthly story. Cash is a Tuesday-morning fact.' },
  ],
  c8d: [
    { q: 'Which cost arrives even in a week where you sell nothing?',
      opts: ['The rent', 'The stock', 'The wrapping paper', 'The delivery fee'], a: 0,
      why: 'Fixed costs do not care that it was quiet. That is exactly why quiet weeks hurt.' },
    { q: '200 rent a month is "seven a day". Why does a shopkeeper carry that number?',
      opts: ['It is what breaking even starts at', 'Rent is paid daily in town', 'Sevens are easy to recall', 'The landlord quotes it so'], a: 0,
      why: 'Before the first sale, the day is already seven down. Knowing your seven is knowing your floor.' },
  ],
};
