/* generated by tools/lessons/process-all.py — do not edit. */
/* Nana Bizz's teaching poses — the cast are animals, and the teacher is
   the tortoise, exactly as her portrait draws her. */
export const POSES = {
  'point': { w: 354, h: 300, src: new URL('./art/lessons-poses-1703ad1175.webp', import.meta.url).href },
  'smile': { w: 303, h: 300, src: new URL('./art/lessons-poses-156eb43ce2.webp', import.meta.url).href },
  'talk': { w: 246, h: 300, src: new URL('./art/lessons-poses-f4fd771066.webp', import.meta.url).href },
};
