/* generated by tools/lessons/process-all.py — do not edit. */
/* every lesson full — Vite gives each dynamic import its own chunk,
   fetched on first watch and then held by the service worker */
export const LOADERS = {
  'c1a': () => import('./lessons/c1a.js'),
  'c1b': () => import('./lessons/c1b.js'),
  'c1c': () => import('./lessons/c1c.js'),
  'c1d': () => import('./lessons/c1d.js'),
  'c2a': () => import('./lessons/c2a.js'),
  'c2b': () => import('./lessons/c2b.js'),
  'c2c': () => import('./lessons/c2c.js'),
  'c2d': () => import('./lessons/c2d.js'),
  'c3a': () => import('./lessons/c3a.js'),
  'c3b': () => import('./lessons/c3b.js'),
  'c3c': () => import('./lessons/c3c.js'),
};
