/* generated by tools/lessons/process-all.py — do not edit. */
/* the single-file variant: chapter 1 speaks, the rest teach in captions
   on the measured-duration clock — a 7 MB "one file" is no courtesy */
export const LOADERS = {
  'c1a': () => import('./lessons/c1a.js'),
  'c1b': () => import('./lessons/c1b.js'),
  'c1c': () => import('./lessons/c1c.js'),
  'c1d': () => import('./lessons/c1d.js'),
  'c2a': () => import('./lessons/c2a.lite.js'),
  'c2b': () => import('./lessons/c2b.lite.js'),
  'c2c': () => import('./lessons/c2c.lite.js'),
  'c2d': () => import('./lessons/c2d.lite.js'),
  'c3a': () => import('./lessons/c3a.lite.js'),
  'c3b': () => import('./lessons/c3b.lite.js'),
  'c3c': () => import('./lessons/c3c.lite.js'),
};
