/* objectives-more.js — the other five strands (docs/05 Part A).

   objectives.js shipped CHOOSE first and says why: it transfers to real life
   fastest and the town already had surfaces that could show it. Everything
   here is the same schema, held to the same three rules — a written
   behaviour, a surface in the town, retrieval that is not the card's own
   drill — and it is concatenated into OBJECTIVES so validate() sees it too.

   Five strands, thirty-six rungs:

   · EARN   what your time is worth, and where money comes in
   · KEEP   what is left, and holding on to it on purpose
   · GROW   what money does when it is left alone
   · OWE    borrowing, and what it costs
   · GUARD  the ones designed to take it off you

   `needs_maths` is the number spine (docs/03 §3), and it is the real gate:
   an objective that needs division is not offered before division. Where a
   rung could be written either as a percent or in coins, it is written in
   coins and the percent is a display format — the rule the Jar Shed broke. */

export const MORE_OBJECTIVES = [
  /* ══ EARN ══════════════════════════════════════════════════════════════ */
  {
    id: 'EARN-1', strand: 'EARN', rung: 1,
    objective: 'Says where each amount in their wallet came from, and which of it was traded for their own time.',
    needs_maths: ['M1'], needs: [], surface: 'place', teach: 'c1c',
    short: 'Where the money came from',
    parent_line: 'Ask her which of the money she has now she worked for. The ones she has to think about are the interesting ones.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'Money arrives in your wallet three ways this week. Which one did your time buy?', opts: ['A birthday gift', 'An hour stacking crates', 'Interest from the bank', 'Money found on the path'], a: 1,
        why: 'Only one of those is a trade. You gave an hour and got money back — the other three arrived without costing you anything you had.' },
      { q: 'Why is it worth knowing which money you worked for?', opts: ['Worked money is worth more', 'Because it is the only kind you can get more of on purpose', 'So you can spend the rest first', 'It is not worth knowing'], a: 1,
        why: 'A gift arrives or it does not. Work is the part you can decide about — so it is the part worth understanding.' },
      { q: 'Somebody says "I got ₹500 this week." What is the useful next question?', opts: ['What will you spend it on?', 'Where did it come from?', 'Is that a lot?', 'Can I have some?'], a: 1,
        why: 'The same number means completely different things depending on whether it repeats. Where it came from tells you whether next week has one too.' },
    ],
  },
  {
    id: 'EARN-2', strand: 'EARN', rung: 2,
    objective: 'Works out what an hour of a job is worth to them, and says it as a rate rather than as a total.',
    needs_maths: ['M4'], needs: ['EARN-1'], surface: 'place', teach: 'c2a',
    short: 'What an hour is worth',
    parent_line: 'Ask what an hour of her time is worth at each of her jobs. Not the total — the rate. The comparison is the whole skill.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'A job pays ₹90 and takes two hours. What is the rate?', opts: ['₹90 an hour', '₹45 an hour', '₹180 an hour', 'You cannot say'], a: 1,
        why: '₹90 shared over two hours is ₹45 each. The total tells you what landed; the rate tells you what your time was worth.' },
      { q: 'Job A pays ₹120 for three hours. Job B pays ₹90 for two. Which pays better?', opts: ['A — it pays more', 'B — ₹45 an hour against ₹40', 'The same', 'It depends how hard they are'], a: 1,
        why: 'A is ₹40 an hour and B is ₹45. The bigger number was the smaller rate, which is exactly why the rate is the one to work out.' },
      { q: 'Why is a rate more useful than a total when you are choosing work?', opts: ['It is a bigger number', 'Because your time is the thing you actually have less of', 'Totals are hard to add', 'Employers prefer it'], a: 1,
        why: 'You can always work more hours until you cannot. The hours are the limit, so what one is worth is the number that decides.' },
    ],
  },
  {
    id: 'EARN-3', strand: 'EARN', rung: 3,
    objective: 'Tells a one-off from something that repeats, and does not plan a week around money that came once.',
    needs_maths: ['M2'], needs: ['EARN-1'], surface: 'wallet', teach: 'c2c',
    short: 'A gift is not a wage',
    parent_line: 'When money arrives from somewhere unusual, ask whether it will come again next week. It is the question that separates a windfall from an income.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: 'A relative gives you ₹1,000. What should you NOT do with that number?', opts: ['Put some in the Save jar', 'Treat it as what arrives every week from now on', 'Spend some of it', 'Put it towards a goal'], a: 1,
        why: 'Every other answer is fine. The one that hurts is building a week around a number that is not coming back.' },
      { q: 'Which of these is income?', opts: ['Finding ₹50 in an old coat', 'A prize', 'Two hours of work every Saturday', 'A one-off gift'], a: 2,
        why: 'Income is the part that repeats. The others are all real money and all worth having — they just cannot be planned on.' },
      { q: 'Your wallet had a very good week because of one gift. What does a careful plan use?', opts: ['The good week', 'The ordinary week', 'The average of the two', 'The best week ever'], a: 1,
        why: 'A plan built on the ordinary week survives the ordinary week. Anything better is then a surprise instead of a shortfall.' },
    ],
  },
  {
    id: 'EARN-4', strand: 'EARN', rung: 4,
    objective: 'Given two pieces of work, picks by what an hour is worth rather than by the size of the payment.',
    needs_maths: ['M6'], needs: ['EARN-2'], surface: 'place', teach: 'c2b',
    short: 'Choosing work by the rate',
    parent_line: 'Give her two made-up jobs where the bigger total is the worse rate. Watching her catch it is the assessment.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'Sweeping pays ₹30 for half an hour. Delivering pays ₹100 for two hours. Which is the better use of an hour?', opts: ['Delivering', 'Sweeping — ₹60 an hour against ₹50', 'Neither, they are equal', 'Delivering, because ₹100 is more'], a: 1,
        why: '₹30 for half an hour is ₹60 an hour. The ₹100 job is ₹50 an hour. The big number is the slower one.' },
      { q: 'When is the lower rate still the right job to take?', opts: ['Never', 'When the higher-rate work is not actually available today', 'When you like it more', 'When it is nearer'], a: 1,
        why: 'A rate you cannot get is not a real option. Comparing is useful only among the jobs actually on the board — the rest is arithmetic about nothing.' },
      { q: 'What does a rate NOT tell you?', opts: ['What an hour is worth', 'How much you will have at the end', 'Which job pays faster', 'How to compare two jobs'], a: 1,
        why: 'A rate times hours is the total, and hours are the thing that runs out. Both numbers matter; the rate is just the one people skip.' },
    ],
  },
  {
    id: 'EARN-5', strand: 'EARN', rung: 5,
    objective: 'Names more than one place their money comes from, and says which one would hurt most to lose.',
    needs_maths: ['M2'], needs: ['EARN-3'], surface: 'place', teach: 'c2d',
    short: 'More than one tap',
    parent_line: 'Ask what she would do if her best-paying job stopped tomorrow. Not to worry her — to notice whether there is a second answer.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'All of somebody\'s money comes from one job. What is the risk?', opts: ['They will get bored', 'If that one stops, everything stops at once', 'They will earn too much', 'There is no risk'], a: 1,
        why: 'One tap is fine until it is turned off. The problem is not the size of the income; it is that there is nothing behind it.' },
      { q: 'Which is steadier over a year?', opts: ['One job paying ₹400 a week', 'Four jobs paying ₹100 a week each', 'They are identical', 'The one job, always'], a: 1,
        why: 'Same total, different risk. Losing one of four costs a quarter; losing one of one costs everything.' },
      { q: 'What does a second source of money buy you, besides money?', opts: ['Nothing', 'The ability to say no to the first one', 'More work', 'A better rate'], a: 1,
        why: 'That is the quiet part. Somebody with only one income cannot walk away from it, and everybody involved knows that.' },
    ],
  },
  {
    id: 'EARN-6', strand: 'EARN', rung: 6,
    objective: 'Gets better at a job on purpose and can say what changed about what their time is worth.',
    needs_maths: ['M6'], needs: ['EARN-4'], surface: 'arcade', teach: 'c2b',
    short: 'Being worth asking twice',
    parent_line: 'Ask what she is better at now than a month ago, and what that is worth. The answer being "nothing yet" is a fine answer honestly given.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'Two people do the same job. One is asked back every week. What is that person selling?', opts: ['Lower prices', 'Being worth asking twice', 'More hours', 'Better luck'], a: 1,
        why: 'Being asked back is worth more than any single day\'s rate, because it turns one payment into many without any new negotiation.' },
      { q: 'You get twice as fast at a job that pays per job, not per hour. What happened to your rate?', opts: ['Nothing', 'It doubled', 'It halved', 'It cannot be worked out'], a: 1,
        why: 'Same money, half the hours, so an hour is now worth twice as much. Getting faster IS a pay rise when the job pays by the job.' },
      { q: 'What is the honest way to ask for more?', opts: ['Say you need it', 'Say what you now do that you did not do before', 'Ask when they are busy', 'Threaten to leave'], a: 1,
        why: 'The reason has to be about what they get, not about what you want. That is the difference between a case and a complaint.' },
    ],
  },
  {
    id: 'EARN-7', strand: 'EARN', rung: 7,
    objective: 'Keeps the money a business took separate from the money they paid themselves, and says which is which.',
    needs_maths: ['M8'], needs: ['EARN-3'], surface: 'wallet', teach: 'c8c',
    short: 'The till is not your pocket',
    parent_line: 'If she runs the stall, ask what the shop made this week and what she took home. If those are the same number, that is the conversation.',
    transfer: ['business'], sources: [],
    assess: [
      { q: 'Your stall took ₹900 this week. How much of that is yours?', opts: ['₹900', 'Whatever is left after what it cost to run', 'Half', 'None of it'], a: 1,
        why: 'Money through the till is not money earned. Stock, rent and what spoiled all come out first, and what is left is the part that was ever yours.' },
      { q: 'Why keep the two apart?', opts: ['To pay less tax', 'So you can tell whether the stall is actually working', 'Because it is the rule', 'To have two piles'], a: 1,
        why: 'If the two mix, a stall that loses money can feel fine for weeks — because the till keeps filling up right until it does not.' },
      { q: 'You take ₹200 out of the till for yourself. What happened to the business?', opts: ['Nothing', 'It has ₹200 less to buy stock with', 'It made ₹200 less', 'It is now worth more'], a: 1,
        why: 'Drawing money out is not a cost and it is not a loss — but the stall now has less to work with, and next week will show it.' },
    ],
  },
  {
    id: 'EARN-8', strand: 'EARN', rung: 8,
    objective: 'Turns irregular earnings into a weekly number they can plan on, and says why they used the low one.',
    needs_maths: ['M9'], needs: ['EARN-5', 'EARN-4'], surface: 'place', teach: 'c3a',
    short: 'A number you can plan on',
    parent_line: 'Ask what she earns in a typical week when the work is not the same every week. Whether she reaches for the average or the worst week tells you a lot.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: 'Four weeks paid ₹200, ₹380, ₹150 and ₹270. What is a week worth on average?', opts: ['₹380', '₹250', '₹150', '₹1,000'], a: 1,
        why: '₹1,000 over four weeks is ₹250 each. That is the number that describes the run, rather than the one you remember best.' },
      { q: 'Which number should the week\'s plan be built on?', opts: ['The best week', 'The average', 'Something at or below the average', 'The total'], a: 2,
        why: 'The average is right half the time and short the other half. A plan that survives the quiet weeks is built a little under it.' },
      { q: 'Why is a bad week worse than an average week is good?', opts: ['It is not', 'Because the bills arrive whatever the week did', 'Because you feel worse', 'Because it lasts longer'], a: 1,
        why: 'The costs do not move with the earnings. That is what makes the low week the one worth planning around.' },
    ],
  },

  /* ══ KEEP ══════════════════════════════════════════════════════════════ */
  {
    id: 'KEEP-1', strand: 'KEEP', rung: 1,
    objective: 'Says what is left after the week\'s costs before spending any of it, and names that number as the part they choose about.',
    needs_maths: ['M5'], needs: [], surface: 'wallet', teach: 'c3a',
    short: 'What is left over',
    parent_line: 'Ask what is left after the week has paid for itself. That number, not the wallet, is the one she is actually choosing with.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: '₹400 comes in and ₹260 goes out on things that arrive anyway. What is the choosing number?', opts: ['₹400', '₹140', '₹260', '₹660'], a: 1,
        why: 'The ₹260 was already spoken for. ₹140 is the only part any decision is actually about.' },
      { q: 'Why work it out BEFORE spending rather than after?', opts: ['It is easier', 'Because afterwards it is a result, not a choice', 'It is not important', 'To have a bigger number'], a: 1,
        why: 'Worked out first, it is a plan. Worked out last, it is just a description of what already happened.' },
      { q: 'What has gone wrong if the left-over is negative?', opts: ['Nothing', 'The week costs more than it brings in, and something must change', 'You counted wrong', 'You need to spend less on treats'], a: 1,
        why: 'It might be the costs, it might be the income, and it might just be this week. But it is a fact to face rather than a mood.' },
    ],
  },
  {
    id: 'KEEP-2', strand: 'KEEP', rung: 2,
    objective: 'Splits money into named jars the moment it lands, using a rule they set earlier rather than deciding on the day.',
    needs_maths: ['M7'], needs: ['KEEP-1'], surface: 'wallet', teach: 'c3b',
    short: 'Split it the moment it lands',
    parent_line: 'Ask what her rule is and when she set it. A rule made on pay day, with the money in front of her, is not really a rule.',
    transfer: ['jars', 'goals'], sources: [],
    assess: [
      { q: 'Why split money as soon as it arrives?', opts: ['It looks tidy', 'Because one pile gets spent as one pile', 'Jars are safer', 'To make it last longer by magic'], a: 1,
        why: 'Money that is all in one place has no name on any of it, and unnamed money goes on whatever comes first.' },
      { q: 'Out of ₹200, a rule sends three parts in ten to Save. How much is that?', opts: ['₹30', '₹60', '₹20', '₹70'], a: 1,
        why: 'A tenth of ₹200 is ₹20, so three of them is ₹60. Three in ten is a rule you can do in your head, which is why it holds.' },
      { q: 'When is the right time to CHANGE the rule?', opts: ['When something you want is just out of reach', 'On an ordinary day when nothing is tempting you', 'Never', 'Every week'], a: 1,
        why: 'A rule changed to reach today\'s thing is not a rule any more. Changing it is fine; changing it in the shop is the problem.' },
    ],
  },
  {
    id: 'KEEP-3', strand: 'KEEP', rung: 3,
    objective: 'Names one cost that arrives whatever they do and one that follows what they do, from their own week.',
    needs_maths: ['M4'], needs: ['KEEP-1'], surface: 'place', teach: 'c3a',
    short: 'The ones that arrive anyway',
    parent_line: 'Ask which of her costs she could change this week and which she could not. The list is short and clarifying.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: 'Which of these arrives whether you do anything or not?', opts: ['A snack', 'Rent', 'A trip to the market', 'A birthday present'], a: 1,
        why: 'Rent turns up on its day regardless. The others all follow a decision, which is what makes them the ones you can move.' },
      { q: 'Money is tight this week. Which line moves first?', opts: ['Rent', 'The ones that follow what you do', 'All of them equally', 'None — you borrow'], a: 1,
        why: 'The variable ones move because they can. Trying to move a fixed one first is how a small problem becomes a late payment.' },
      { q: 'Why is a big fixed cost more serious than a big variable one?', opts: ['It is not', 'Because you cannot turn it off in a bad week', 'Because it is usually larger', 'Because it is paid first'], a: 1,
        why: 'A variable cost is a decision you can make again. A fixed one is a decision you already made, and it keeps arriving.' },
    ],
  },
  {
    id: 'KEEP-4', strand: 'KEEP', rung: 4,
    objective: 'Turns something they want into a number of weeks at their own saving rate, and says the date rather than a wish.',
    needs_maths: ['M8'], needs: ['KEEP-2'], surface: 'wallet', teach: 'c3d',
    short: 'Turning a wish into a date',
    parent_line: 'Ask how many weeks away the thing she wants is. A number, not "soon" — dividing is what turns wanting into planning.',
    transfer: ['goals'], sources: [],
    assess: [
      { q: 'A ₹900 thing, saving ₹75 a week. How many weeks?', opts: ['9', '12', '15', '6'], a: 1,
        why: '₹900 divided by ₹75 is 12. Not "one day" — twelve weeks, which is a thing you can put on a calendar and watch shrink.' },
      { q: 'You double what you save each week. What happens to the wait?', opts: ['It doubles', 'It halves', 'It stays the same', 'It quarters'], a: 1,
        why: 'Twice the rate, half the time. That is the trade the number lets you see: more each week, or the same wait with more left over.' },
      { q: 'Why is a number of weeks more useful than "I am saving up"?', opts: ['It sounds better', 'Because you can tell whether it is worth it before you start', 'It is faster', 'Adults prefer it'], a: 1,
        why: 'Thirty weeks for a small thing changes the answer. Knowing before you start is the whole point of working it out.' },
    ],
  },
  {
    id: 'KEEP-5', strand: 'KEEP', rung: 5,
    objective: 'Leaves a funded goal alone when something else is tempting, and says what they did instead of raiding it.',
    needs_maths: ['M2'], needs: ['KEEP-4'], surface: 'store', teach: 'x-ch11',
    short: 'Leaving the goal alone',
    parent_line: 'When she wants something and the goal money is right there, ask what else could pay for it. The answer is often "nothing, so not this week" — and that is the win.',
    transfer: ['goals'], sources: [],
    assess: [
      { q: 'You raid a goal for something else. What did it cost?', opts: ['Nothing, it is your money', 'The weeks you have to do again', 'The price of the thing', 'Your Save jar'], a: 1,
        why: 'The money comes back eventually. The weeks do not, and they were the expensive part all along.' },
      { q: 'What makes a goal easier to leave alone?', opts: ['Hiding it', 'Having a name and a date on it', 'Making it bigger', 'Not looking at it'], a: 1,
        why: 'An unnamed pile is just money. A named one with a date is a thing you are already halfway to, and raiding it feels like what it is.' },
      { q: 'When is spending the goal money the right call?', opts: ['Never', 'When something genuinely more important than the goal has happened', 'When you have waited long enough', 'When it is nearly full'], a: 1,
        why: 'It is your money and sometimes life reorders itself. The rule is that it should be a decision you would still defend next week.' },
    ],
  },
  {
    id: 'KEEP-6', strand: 'KEEP', rung: 6,
    objective: 'When money coming in falls, cuts the variable costs first and can say why that order matters.',
    needs_maths: ['M6'], needs: ['KEEP-3'], surface: 'place', teach: 'c3a',
    short: 'Which line moves first',
    parent_line: 'Give her a week where the money is short and ask what she would change. Watch whether she reaches for the moveable things first.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: 'Income drops by ₹100. What is the first place to look?', opts: ['Rent', 'The things that follow what you do', 'Borrowing', 'The Save jar'], a: 1,
        why: 'They move without a phone call, a notice period, or anybody else agreeing. That makes them first, not smallest.' },
      { q: 'Why not stop saving first?', opts: ['You should stop saving first', 'Because it is the one line that is the point of the whole plan', 'Because saving is compulsory', 'Because it is small'], a: 1,
        why: 'Stopping saving works, and sometimes it is right. But it is the last thing that ever gets easier, so it is not where you start.' },
      { q: 'The income drop looks permanent. What now?', opts: ['Cut the same variable things harder each week', 'Look at the fixed costs, because the situation changed', 'Borrow the difference', 'Wait for it to recover'], a: 1,
        why: 'Variable cuts get a household through a bad month. A changed situation needs the big, slow lines to change too — moving house, or a different plan.' },
    ],
  },
  {
    id: 'KEEP-7', strand: 'KEEP', rung: 7,
    objective: 'Uses their own record to answer a question about a past week, rather than guessing from memory.',
    needs_maths: ['M5'], needs: ['KEEP-1'], surface: 'jars', teach: 'c3a',
    short: 'Checking, not remembering',
    parent_line: 'Ask what she spent most on last week. If she guesses, ask her to look — the gap between the guess and the record is the lesson.',
    transfer: ['wallet'], sources: [],
    assess: [
      { q: 'You think you spent about ₹200 on snacks last week. How do you find out?', opts: ['Think harder', 'Add up the actual lines', 'Ask a friend', 'Assume you were right'], a: 1,
        why: 'Memory rounds down the small repeated ones — that is not a character flaw, it is just how remembering works. The record does not.' },
      { q: 'Why do the small repeated costs surprise people most?', opts: ['They are hidden', 'Because each one is too small to remember and there are many', 'They are not surprising', 'Because they are new'], a: 1,
        why: 'Nobody forgets the one big thing. Twenty small ones are individually forgettable and collectively the answer.' },
      { q: 'What is a record actually for?', opts: ['Proving what you spent', 'Answering a question later that you cannot answer now', 'Making you feel bad', 'Showing a grown-up'], a: 1,
        why: 'Not surveillance, and not a scorecard. It is a way of asking your past self a question and getting a straight answer.' },
    ],
  },
  {
    id: 'KEEP-8', strand: 'KEEP', rung: 8,
    objective: 'Says what money set aside for surprises is for, and why it is not the same as saving for a thing.',
    needs_maths: ['M5'], needs: ['KEEP-4'], surface: 'bank', teach: 'c5a',
    short: 'The pile with no name on it',
    parent_line: 'Ask what would happen if something broke this week. Whether there is an answer that is not "borrow" is the whole question.',
    transfer: ['jars'], sources: [],
    assess: [
      { q: 'What is money set aside for surprises for?', opts: ['A holiday', 'The thing you did not plan for', 'A bigger goal', 'Interest'], a: 1,
        why: 'It is the only pile whose job is to have no job. That is exactly what makes it useful when something goes wrong.' },
      { q: 'How is it different from a goal?', opts: ['It is bigger', 'A goal is for something chosen; this is for something that happens to you', 'It is not different', 'It earns more'], a: 1,
        why: 'You choose a goal. You do not choose a burst pipe — so a pile you are allowed to spend on nothing is the one that answers it.' },
      { q: 'Somebody has no set-aside money and something breaks. What usually happens?', opts: ['Nothing', 'They borrow, and the surprise now costs more than it did', 'They save faster', 'The thing fixes itself'], a: 1,
        why: 'The surprise is the same size either way. Having nothing set aside is what adds interest to it.' },
    ],
  },

  /* ══ GROW ══════════════════════════════════════════════════════════════ */
  {
    id: 'GROW-1', strand: 'GROW', rung: 1,
    objective: 'Says what a bank does with money left with it, and why it pays for the privilege of holding it.',
    needs_maths: ['M3'], needs: [], surface: 'jars', teach: 'c5a',
    short: 'What a bank is for',
    parent_line: 'Ask where she thinks the money in a bank actually is. "In a big safe" is the usual answer and the interesting one.',
    transfer: ['bank'], sources: [],
    assess: [
      { q: 'Your money is in a bank. Where is it?', opts: ['In a drawer with your name on it', 'Lent out to somebody else', 'In a safe under the building', 'Nowhere — it is only a number'], a: 1,
        why: 'The bank lends it on. That is why they want it, and why they pay you a little to leave it there.' },
      { q: 'Why does a bank pay you interest?', opts: ['To be kind', 'Because your money is useful to them', 'Because it is the law', 'To make up for inflation'], a: 1,
        why: 'It is rent on money. They can earn more with it than they pay you, and both sides come out ahead — which is what a working trade looks like.' },
      { q: 'What is the bank actually giving you besides interest?', opts: ['Nothing', 'Somewhere it is not in your pocket to spend', 'Free money', 'A card'], a: 1,
        why: 'Distance from your own hands is worth real money — sometimes more than the interest is.' },
    ],
  },
  {
    id: 'GROW-2', strand: 'GROW', rung: 2,
    objective: 'Works out one period\'s interest on a balance, and can say it in coins as well as as a rate.',
    needs_maths: ['M10'], needs: ['GROW-1'], surface: 'jars', teach: 'c6a',
    short: 'Interest, in coins',
    parent_line: 'Ask what 2% of ₹500 is in rupees. If the percent gets in the way, ask what two in every hundred rupees comes to — same question, no percent.',
    transfer: ['bank'], sources: [],
    assess: [
      { q: '₹500 in the bank at 2% a period. What lands?', opts: ['₹2', '₹10', '₹20', '₹50'], a: 1,
        why: 'Two in every hundred, and there are five hundreds — so ₹10. Saying it in coins is what stops a percent hiding the size.' },
      { q: 'The same 2% on ₹5,000?', opts: ['₹10', '₹100', '₹50', '₹500'], a: 1,
        why: 'The rate did not change; the pile did. A percent is always a rate about a number, and never a size on its own.' },
      { q: 'Which pays more: 5% on ₹200 or 2% on ₹1,000?', opts: ['5% on ₹200', '2% on ₹1,000', 'The same', 'Cannot compare'], a: 1,
        why: '₹10 against ₹20. The bigger rate on the smaller pile lost, which is why you turn both into coins before deciding.' },
    ],
  },
  {
    id: 'GROW-3', strand: 'GROW', rung: 3,
    objective: 'Explains why the second period earns more than the first without anything new being added.',
    needs_maths: ['M11'], needs: ['GROW-2'], surface: 'jars', teach: 'c7a',
    short: 'Why the second time is bigger',
    parent_line: 'Ask why the interest is bigger the second time when she put nothing in. Getting to "because the interest is earning too" is the moment.',
    transfer: ['bank'], sources: [],
    assess: [
      { q: '₹1,000 earns ₹100. Next period, the same rate earns more. Why?', opts: ['The rate went up', 'It is now working on ₹1,100', 'The bank was generous', 'It did not'], a: 1,
        why: 'The interest joined the pile and started earning. Nothing else changed, and that is the whole of compounding.' },
      { q: 'What makes the difference get bigger over time?', opts: ['Nothing, it is steady', 'Each period\'s gain is added before the next one is worked out', 'The rate rises', 'You add more'], a: 1,
        why: 'It builds on itself. Early on it is dull and nearly invisible; late on it is the biggest thing in the sum.' },
      { q: 'Somebody takes their interest out each period instead of leaving it. What happens?', opts: ['They earn more', 'The pile stops growing on itself and every period pays the same', 'Nothing changes', 'The bank pays a higher rate'], a: 1,
        why: 'Taking it out is a perfectly reasonable thing to do — it just turns a snowball back into a wage.' },
    ],
  },
  {
    id: 'GROW-4', strand: 'GROW', rung: 4,
    objective: 'Given two possible returns, says which is higher and names what is being risked to get it.',
    needs_maths: ['M10'], needs: ['GROW-2'], surface: 'bank', teach: 'c7b',
    short: 'What the extra costs',
    parent_line: 'Ask why anybody would take the lower return. The answer is the whole of risk, and it is not obvious at first.',
    transfer: ['portfolio'], sources: [],
    assess: [
      { q: 'One thing might pay 3%, another might pay 15%. What comes with the 15%?', opts: ['Nothing, it is just better', 'A real chance of getting less, or losing some', 'A longer wait', 'A bigger fee'], a: 1,
        why: 'Nobody offers more for free. The extra is the price of a possibility, and the possibility is that it does not happen.' },
      { q: '"Might pay 15%" — what is the word doing?', opts: ['Nothing, it is politeness', 'It is the entire warning', 'It means at least 15%', 'It means about 15%'], a: 1,
        why: 'Might is the honest word in the sentence. Everything that goes wrong with investing goes wrong in that word.' },
      { q: 'When is the safer, lower return the right choice?', opts: ['Never', 'When you need the money at a particular time', 'When you are young', 'When rates are high'], a: 1,
        why: 'Risk is not just about how much; it is about when. Money that has to be there on a date cannot afford a bad year.' },
    ],
  },
  {
    id: 'GROW-5', strand: 'GROW', rung: 5,
    objective: 'Spreads money across more than one holding and can say what that protects them from.',
    needs_maths: ['M8'], needs: ['GROW-4'], surface: 'bank', teach: 'c7c',
    short: 'Never just one',
    parent_line: 'Ask what happens if the one thing she picked has a bad year. "Then I lose" is correct, and it is the reason for the next question.',
    transfer: ['portfolio'], sources: [],
    assess: [
      { q: 'All of somebody\'s money is in one company. What is the danger?', opts: ['They will get bored', 'One thing going wrong takes everything with it', 'They will earn less', 'There is none'], a: 1,
        why: 'A spread does not make the good years better. It makes the bad year survivable, which turns out to be the important half.' },
      { q: 'What does spreading NOT protect against?', opts: ['One company failing', 'A bad year for everything at once', 'One shop closing', 'A single bad guess'], a: 1,
        why: 'When everything falls together, spreading does not help. It is protection against being wrong about one thing, not against a bad year.' },
      { q: 'Why is the boring spread choice often the winner over years?', opts: ['It is not', 'Because it never has the year that wipes it out', 'Because it earns most', 'Because it is cheaper'], a: 1,
        why: 'You cannot compound from zero. Avoiding the disaster year beats winning the good one, and that is a deeply unexciting truth.' },
    ],
  },
  {
    id: 'GROW-6', strand: 'GROW', rung: 6,
    objective: 'Does nothing on a day everything falls, and can say afterwards that doing nothing was the decision.',
    needs_maths: ['M6'], needs: ['GROW-5'], surface: 'bank', teach: 'c7d',
    short: 'Doing nothing on purpose',
    parent_line: 'Ask what she did on the red day. If the answer is "nothing", ask whether that was a decision or an accident — the difference is the skill.',
    transfer: ['portfolio'], sources: [],
    assess: [
      { q: 'Everything drops and everyone says sell. Selling turns what into what?', opts: ['A loss into a gain', 'A number on a screen into a real loss', 'Nothing', 'A risk into safety'], a: 1,
        why: 'Until you sell, it is a price. Selling is the step that makes it money you no longer have.' },
      { q: 'Why is doing nothing so hard?', opts: ['It is easy', 'Because it feels like not doing your job while everybody else is busy', 'Because it costs money', 'Because it is against the rules'], a: 1,
        why: 'Every instinct says act. That is exactly why the people who do nothing on the red day are the ones who are still there afterwards.' },
      { q: 'When is selling on a fall actually right?', opts: ['Never', 'When you were going to need that money soon anyway', 'When it drops 10%', 'When the news is bad'], a: 1,
        why: 'The mistake is not selling; it is selling because of the fall. Selling because you need the money is a different act entirely.' },
    ],
  },
  {
    id: 'GROW-7', strand: 'GROW', rung: 7,
    objective: 'Says what years do to a small regular amount, and that starting earlier beats adding more later.',
    needs_maths: ['M12'], needs: ['GROW-3'], surface: 'bank', teach: 'c7d',
    short: 'Time is the ingredient',
    parent_line: 'Ask which she would rather have: ₹50 a week starting now, or ₹100 a week starting in ten years. Nobody guesses this right first time.',
    transfer: ['goals'], sources: [],
    assess: [
      { q: 'Two people save the same amount each week. One starts ten years earlier. What did the early one buy?', opts: ['Nothing', 'Ten years of growing on itself', 'A better rate', 'Less risk'], a: 1,
        why: 'The years are doing work no extra saving can catch up with, because they compound on everything already there.' },
      { q: 'Which is the hardest part of compounding to believe?', opts: ['That it works', 'That almost nothing happens for a long time and then a lot happens', 'That it needs a bank', 'That it needs a lot of money'], a: 1,
        why: 'The early years look like nothing is happening. Most people stop there — and stopping there is exactly what removes the effect.' },
      { q: 'What is the smallest useful amount to start with?', opts: ['Whatever you can actually keep doing', 'Nothing under ₹1,000', 'Half your money', 'It does not matter'], a: 0,
        why: 'A small amount you keep up beats a big one you stop. The habit is the mechanism; the size is only the speed.' },
    ],
  },
  {
    id: 'GROW-8', strand: 'GROW', rung: 8,
    objective: 'Separates money they can leave alone for years from money they need soon, and puts each somewhere different.',
    needs_maths: ['M8'], needs: ['GROW-4', 'KEEP-8'], surface: 'bank', teach: 'c7b',
    short: 'Money you can leave alone',
    parent_line: 'Ask which of her money she will not touch for a year. That question, not the return, is what decides where it should sit.',
    transfer: ['portfolio', 'jars'], sources: [],
    assess: [
      { q: 'Money you might need next month — where does it belong?', opts: ['Somewhere it might fall', 'Somewhere safe and reachable', 'In a long investment', 'Spread across shares'], a: 1,
        why: 'When you need it decides where it sits. A good investment that is down in the month you need it is a bad plan.' },
      { q: 'What lets money be invested rather than saved?', opts: ['Having a lot of it', 'Being able to leave it alone through a bad stretch', 'A good tip', 'A high rate'], a: 1,
        why: 'The ability to wait is the whole qualification. Without it, the risk is not a risk you are taking — it is one taking you.' },
      { q: 'Somebody invests their surprise money and something breaks in a bad month. What happened?', opts: ['They are fine', 'They have to sell at the worst moment', 'They earn more', 'Nothing'], a: 1,
        why: 'It is the same money, in the wrong place. The market did not do anything unusual; the plan asked it to be somewhere it never was.' },
    ],
  },

  /* ══ OWE ═══════════════════════════════════════════════════════════════ */
  {
    id: 'OWE-1', strand: 'OWE', rung: 1,
    objective: 'Says that borrowing has a price and names it, without treating borrowing itself as a wrong thing.',
    needs_maths: ['M6'], needs: [], surface: 'bank', teach: 'c6a',
    short: 'Borrowing has a price',
    parent_line: 'Ask what borrowing costs. Not whether it is bad — what it costs. It is a tool with a price, and the price is the part to know.',
    transfer: ['loans'], sources: [],
    assess: [
      { q: 'You borrow ₹500 and pay back ₹560. What was the ₹60?', opts: ['A mistake', 'The price of having the money sooner', 'A fine', 'A gift to the bank'], a: 1,
        why: 'You rented money for a while. ₹60 is the rent, and it bought you the time between then and now.' },
      { q: 'Is borrowing a bad thing to do?', opts: ['Always', 'It is a tool with a price — the question is whether the price is worth it', 'Never', 'Only for big things'], a: 1,
        why: 'Shaming debt teaches nothing useful. Knowing the price and deciding is the skill, and it works in both directions.' },
      { q: 'Somebody says a loan is "interest free". What should you check?', opts: ['Nothing, that is good news', 'What else it costs — a fee, a higher price, a penalty later', 'The bank\'s name', 'The colour of the form'], a: 1,
        why: 'Money is not usually lent for nothing. If the interest is not the price, look for where the price went.' },
    ],
  },
  {
    id: 'OWE-2', strand: 'OWE', rung: 2,
    objective: 'Reads the total they will hand over before agreeing, rather than the size of the weekly payment.',
    needs_maths: ['M9'], needs: ['OWE-1'], surface: 'store', teach: 'c6b',
    short: 'The number that matters',
    parent_line: 'When an advert says "only ₹X a week", ask her what it comes to. Multiplying is the entire defence.',
    transfer: ['loans'], sources: [],
    assess: [
      { q: '"Only ₹40 a week for 24 weeks." What are you agreeing to?', opts: ['₹40', '₹960', '₹240', 'It does not say'], a: 1,
        why: '₹40 × 24 = ₹960. The small number is the one you are shown; the big one is the one you are agreeing to.' },
      { q: 'Why do offers advertise the weekly payment?', opts: ['It is more honest', 'Because it is the smallest true number they can show you', 'It is easier to calculate', 'To help you budget'], a: 1,
        why: 'Every part of it is true, and the total is still the thing you need. It is not a lie; it is a choice about which truth to show.' },
      { q: 'Two loans for the same thing. One is ₹30 a week for 40 weeks, one is ₹50 for 22. Which costs less?', opts: ['The ₹30 one', 'The ₹50 one — ₹1,100 against ₹1,200', 'The same', 'The one with the lower weekly'], a: 1,
        why: 'The smaller weekly payment cost ₹100 more in the end. That gap is where the whole trick lives.' },
    ],
  },
  {
    id: 'OWE-3', strand: 'OWE', rung: 3,
    objective: 'Names a good reason and a bad reason to borrow from their own situation, not from a general rule.',
    needs_maths: ['M4'], needs: ['OWE-1'], surface: 'bank', teach: 'c6c',
    short: 'Good reasons and bad ones',
    parent_line: 'Ask her for one thing worth borrowing for and one that is not. Her own examples are worth more than any list.',
    transfer: ['loans'], sources: [],
    assess: [
      { q: 'Which is the better reason to borrow?', opts: ['Something that will earn more than the loan costs', 'Something you want today', 'Something on offer', 'Something everybody has'], a: 0,
        why: 'A cart that pays for itself covers its own interest. That is the whole of a good reason, and it is checkable.' },
      { q: 'Borrowing for something that is gone by the time you finish paying — what is wrong with it?', opts: ['Nothing', 'You keep paying for something you no longer have', 'It costs more', 'It is against the rules'], a: 1,
        why: 'The payments outlive the thing. That is not a moral failing; it is just the worst shape a deal can have.' },
      { q: 'Is "everybody borrows for this" a reason?', opts: ['Yes', 'No — it tells you nothing about your own numbers', 'Only for houses', 'Only for small amounts'], a: 1,
        why: 'What other people do is information about other people. Your own total, and what it buys you, is the only reason that holds.' },
    ],
  },
  {
    id: 'OWE-4', strand: 'OWE', rung: 4,
    objective: 'Makes a repayment when something else wants the money, and names what they gave up to make it.',
    needs_maths: ['M5'], needs: ['OWE-2'], surface: 'bank', teach: 'c6d',
    short: 'Paying it when you would rather not',
    parent_line: 'When a repayment is due and something else is tempting, ask what the repayment cost her this week. Naming it out loud is the point.',
    transfer: ['loans'], sources: [],
    assess: [
      { q: 'A repayment is due and you want something else. What is the honest way to see it?', opts: ['The repayment is unfair', 'The thing you want costs the repayment plus its own price', 'The money is not really yours', 'Skip it this once'], a: 1,
        why: 'You already spent this money when you borrowed. Today is just when it leaves — and anything else you buy is on top of that.' },
      { q: 'What happens when a repayment is missed?', opts: ['Nothing', 'It usually costs more, and it is remembered', 'It disappears', 'It moves to next year'], a: 1,
        why: 'Missing costs twice: a charge now and a smaller offer next time. Neither is punishment; both are the lender pricing what they saw.' },
      { q: 'You cannot make a payment. What is the strong move?', opts: ['Say nothing and hope', 'Tell them before it is due', 'Borrow from somewhere else', 'Pay half quietly'], a: 1,
        why: 'Told early, it is usually a conversation. Discovered late, it is a problem — and that difference is entirely in the telling.' },
    ],
  },
  {
    id: 'OWE-5', strand: 'OWE', rung: 5,
    objective: 'Says how what they can borrow next time changes, in both directions, according to what they did this time.',
    needs_maths: ['M4'], needs: ['OWE-4'], surface: 'loans', teach: 'c6d',
    short: 'Trust is a memory',
    parent_line: 'Ask what the bank remembers about her. That a record works in both directions is easy to miss and worth saying.',
    transfer: ['bank'], sources: [],
    assess: [
      { q: 'Somebody repaid everything on time for a year. What changed?', opts: ['Nothing', 'They can borrow more, and usually for less', 'They owe more', 'The rate went up'], a: 1,
        why: 'A record of paying is worth money. It is the only thing a lender has to go on, so it is priced.' },
      { q: 'What does a lender actually not know about you?', opts: ['Whether you will pay next time', 'Your name', 'What you borrowed before', 'What you paid'], a: 0,
        why: 'They can only see backwards. That is why the past is priced so heavily — it is the only evidence there is.' },
      { q: 'A record is damaged. Can it be repaired?', opts: ['Never', 'Yes, by a run of kept payments — slowly', 'Instantly, by paying it off', 'Only by moving bank'], a: 1,
        why: 'It goes up slowly and down quickly, which is unfair-feeling and true. Knowing that in advance changes how much a missed one matters.' },
    ],
  },
  {
    id: 'OWE-6', strand: 'OWE', rung: 6,
    objective: 'Puts the cost of waiting and the cost of borrowing in the same units before choosing between them.',
    needs_maths: ['M9'], needs: ['OWE-2', 'KEEP-4'], surface: 'goals', teach: 'x-ch8',
    short: 'Waiting against borrowing',
    parent_line: 'Ask what three weeks of having something is worth to her, in rupees. There is no right answer and that is what makes it a real question.',
    transfer: ['store', 'loans'], sources: [],
    assess: [
      { q: '₹800 now with ₹80 of interest, or ₹800 in three weeks. What are you actually choosing?', opts: ['Between good and bad', 'Whether three weeks of having it is worth ₹80 to you', 'The cheaper option', 'Whether to save'], a: 1,
        why: 'Both are legitimate. Once it is put like that, it is a preference with a price on it rather than a test you can fail.' },
      { q: 'When does borrowing win that comparison outright?', opts: ['Never', 'When having it sooner earns or saves more than the interest', 'When you want it a lot', 'When the interest is small'], a: 1,
        why: 'If the cart earns ₹200 in the three weeks it costs ₹80 to have early, waiting is the expensive option.' },
      { q: 'What makes this comparison possible at all?', opts: ['Knowing both totals', 'Guessing', 'Asking somebody', 'The advert'], a: 0,
        why: 'You cannot weigh two things until they are in the same units. Working out both totals is the entire move.' },
    ],
  },

  /* ══ GUARD ═════════════════════════════════════════════════════════════ */
  {
    id: 'GUARD-1', strand: 'GUARD', rung: 1,
    objective: 'Names the things that are never given out, and does not give them out when asked convincingly.',
    needs_maths: ['M1'], needs: [], surface: 'place', teach: 'c5b',
    short: 'The three secrets',
    parent_line: 'Ask what she would never tell anyone, however official they sounded. Then ask what she would do if somebody official asked.',
    transfer: ['letter'], sources: [],
    assess: [
      { q: 'Somebody from "the bank" phones and asks for your PIN to check something. What do you do?', opts: ['Give it — they are from the bank', 'Give nothing and hang up', 'Give half of it', 'Ask them to prove it, then give it'], a: 1,
        why: 'A real bank never needs it. Anybody asking has told you what they are by asking, whatever else they say.' },
      { q: 'Why is "they knew my name and address" not proof?', opts: ['It is proof', 'Because those are easy to find out', 'Because names change', 'Because addresses are public'], a: 1,
        why: 'The easy facts are the ones a stranger can get. Knowing them is exactly how a stranger stops feeling like a stranger.' },
      { q: 'A message says your account will close unless you confirm your password now. What is the tell?', opts: ['The account name', 'The now', 'The spelling', 'The logo'], a: 1,
        why: 'Urgency plus a secret is the whole shape. Real problems keep until you can ring the number on your own card.' },
    ],
  },
  {
    id: 'GUARD-2', strand: 'GUARD', rung: 2,
    objective: 'Describes the shape of a scam rather than its story, and recognises the same shape in a new one.',
    needs_maths: ['M2'], needs: ['GUARD-1'], surface: 'place', teach: 'c5c',
    short: 'The shape, not the story',
    parent_line: 'Ask what two very different scams have in common. Getting past the stories to the shape is the transferable part.',
    transfer: ['letter'], sources: [],
    assess: [
      { q: 'What do almost all scams have in common?', opts: ['Bad spelling', 'Hurry, a secret, and a stranger', 'Foreign names', 'Large amounts'], a: 1,
        why: 'The stories change every year. The shape does not, which is why learning the shape outlasts learning the examples.' },
      { q: 'Why is "it looked professional" not reassuring?', opts: ['It is reassuring', 'Because looking professional is the cheapest part to copy', 'Because professionals are dishonest', 'Because logos are illegal'], a: 1,
        why: 'A convincing appearance costs almost nothing to produce. It is evidence of effort, not of honesty.' },
      { q: 'A brand-new scam nobody has warned you about arrives. What still works?', opts: ['Nothing', 'Checking the shape: who, how fast, and what are they asking for', 'Searching the story', 'Asking the sender'], a: 1,
        why: 'You cannot memorise a list of tricks that is written faster than you read. The shape is the thing that keeps working.' },
    ],
  },
  {
    id: 'GUARD-3', strand: 'GUARD', rung: 3,
    objective: 'Notices hurry being applied to them and slows down on purpose, saying what the hurry was for.',
    needs_maths: ['M2'], needs: ['GUARD-2'], surface: 'place', teach: 'c4a',
    short: 'Hurry is a tool',
    parent_line: 'Point at a countdown or a "today only" sign together and ask what it is for. Naming the technique takes most of its power away.',
    transfer: ['store'], sources: [],
    assess: [
      { q: '"Only 2 left! Offer ends in 10 minutes!" What is that for?', opts: ['Being helpful', 'Stopping you from thinking', 'Managing stock', 'Being fair to everyone'], a: 1,
        why: 'Thinking is the thing that costs them the sale. Hurry is not an accident; it is the tool for removing it.' },
      { q: 'What is the cheapest defence against hurry?', opts: ['Buying quickly', 'Sleeping on it', 'Asking the price', 'Reading the reviews'], a: 1,
        why: 'A day later the feeling is gone and the thing is either still wanted or it is not. Almost every real offer survives a night.' },
      { q: 'A genuinely limited offer exists. How can you tell?', opts: ['You often cannot, and that is the point', 'It says so', 'It has a timer', 'It is in a shop'], a: 0,
        why: 'Real and fake scarcity look identical from outside. Since you cannot tell, decide on whether you want it, not on the clock.' },
    ],
  },
  {
    id: 'GUARD-4', strand: 'GUARD', rung: 4,
    objective: 'Finds who pays when something is offered free, and says what is being given instead of money.',
    needs_maths: ['M3'], needs: ['GUARD-2'], surface: 'store', teach: 'c4b',
    short: 'Free is never free',
    parent_line: 'Next time something is free, ask together who is paying for it. Attention, information, and a habit are all real prices.',
    transfer: ['letter'], sources: [],
    assess: [
      { q: 'A game is free. Who is paying for it to exist?', opts: ['Nobody', 'Somebody, in money or attention or information', 'The government', 'The players who lose'], a: 1,
        why: 'Somebody paid for the building and the people. Finding out who tells you what the thing is really for.' },
      { q: '"Free with any purchase" — what is that?', opts: ['A gift', 'Part of the price of the thing you bought', 'A mistake', 'A discount'], a: 1,
        why: 'You paid for both. The word free is doing work on how the price feels, not on what it is.' },
      { q: 'A free trial that needs your card. What is being sold?', opts: ['The trial', 'The chance that you forget to cancel', 'Nothing', 'Convenience'], a: 1,
        why: 'The business model is forgetting. That is not illegal and it is not hidden — it is just the actual product.' },
    ],
  },
  {
    id: 'GUARD-5', strand: 'GUARD', rung: 5,
    objective: 'Turns a small repeating charge into its yearly number before agreeing to it.',
    needs_maths: ['M9'], needs: ['GUARD-4'], surface: 'place', teach: 'c4c',
    short: 'The small monthly one',
    parent_line: 'Take one subscription in the house and work out the year with her. The number is usually a surprise to everybody at the table.',
    transfer: ['store'], sources: [],
    assess: [
      { q: '₹99 a month. What is the number to say out loud?', opts: ['₹99', '₹1,188 a year', '₹1,000', 'It depends'], a: 1,
        why: '₹99 × 12. Small monthly amounts are designed to be compared to a coffee rather than to a year, and the year is the real size.' },
      { q: 'Why are subscriptions harder to notice than one big purchase?', opts: ['They are not', 'Because you decide once and pay many times', 'Because they are small', 'Because they are online'], a: 1,
        why: 'One decision, many payments, and no reminder. The payments keep happening long after the decision is forgotten.' },
      { q: 'What is the useful habit with anything that repeats?', opts: ['Cancel everything', 'Check once a year whether you still use it', 'Never subscribe', 'Pay yearly'], a: 1,
        why: 'Subscriptions are fine when they are used. The review is what stops the unused ones running for years.' },
    ],
  },
  {
    id: 'GUARD-6', strand: 'GUARD', rung: 6,
    objective: 'Tells a grown-up when something about money feels wrong, and says why telling is the strong move.',
    needs_maths: ['M1'], needs: ['GUARD-1'], surface: 'place', teach: 'c5d',
    short: 'Telling someone is the answer',
    parent_line: 'Say plainly that if she is ever caught by one of these, you want to be told and nobody will be cross. Say it before it happens.',
    transfer: ['letter'], sources: [],
    assess: [
      { q: 'Somebody has tricked you out of money. What is the first move?', opts: ['Fix it quietly', 'Tell a grown-up straight away', 'Pretend it did not happen', 'Try to get it back yourself'], a: 1,
        why: 'Speed is the only thing that ever helps, and shame is what slows people down. Telling early is what makes it fixable.' },
      { q: 'Why do scammers ask people to keep it secret?', opts: ['Politeness', 'Because one other person would end it in a sentence', 'It is more efficient', 'Legal reasons'], a: 1,
        why: 'Secrecy is not a side effect; it is the mechanism. A second pair of eyes is what the whole thing is built to avoid.' },
      { q: 'Is being caught by a scam a sign of being foolish?', opts: ['Yes', 'No — they are designed by people who do it all day', 'Only for adults', 'Only for large amounts'], a: 1,
        why: 'They are professionally made to work on careful people. Believing otherwise is exactly what keeps somebody quiet afterwards.' },
    ],
  },
];
